#pragma once

#define VER_MAJOR 1
#define VER_MINOR 1
#define VER_BUILD 346
#define VER_REVISION 260505

#define STRINGIZE2(x) #x
#define STRINGIZE(x) STRINGIZE2(x)

#define VER_FILEVERSION_STR STRINGIZE(VER_MAJOR) "." STRINGIZE(VER_MINOR) "." STRINGIZE(VER_BUILD) "." STRINGIZE(VER_REVISION)
#define VER_PRODUCTVERSION_STR VER_FILEVERSION_STR
