namespace BeeUi
{
    partial class QuickSetting
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(QuickSetting));
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel5 = new System.Windows.Forms.TableLayoutPanel();
            this.btnClose = new BeeInterface.RJButton();
            this.btnSave = new BeeInterface.RJButton();
            this.adjustBarEx5 = new BeeInterface.AdjustBarEx();
            this.rjButton5 = new BeeInterface.RJButton();
            this.adjustBarEx4 = new BeeInterface.AdjustBarEx();
            this.rjButton4 = new BeeInterface.RJButton();
            this.adjustBarEx3 = new BeeInterface.AdjustBarEx();
            this.rjButton3 = new BeeInterface.RJButton();
            this.adjustBarEx2 = new BeeInterface.AdjustBarEx();
            this.rjButton2 = new BeeInterface.RJButton();
            this.adjustBarEx1 = new BeeInterface.AdjustBarEx();
            this.rjButton1 = new BeeInterface.RJButton();
            this.numFlowChart = new BeeInterface.AdjustBarEx();
            this.btnP1 = new BeeInterface.RJButton();
            this.tableLayoutPanel1.SuspendLayout();
            this.tableLayoutPanel5.SuspendLayout();
            this.SuspendLayout();
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel5, 0, 12);
            this.tableLayoutPanel1.Controls.Add(this.adjustBarEx5, 0, 11);
            this.tableLayoutPanel1.Controls.Add(this.rjButton5, 0, 10);
            this.tableLayoutPanel1.Controls.Add(this.adjustBarEx4, 0, 9);
            this.tableLayoutPanel1.Controls.Add(this.rjButton4, 0, 8);
            this.tableLayoutPanel1.Controls.Add(this.adjustBarEx3, 0, 7);
            this.tableLayoutPanel1.Controls.Add(this.rjButton3, 0, 6);
            this.tableLayoutPanel1.Controls.Add(this.adjustBarEx2, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.rjButton2, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.adjustBarEx1, 0, 5);
            this.tableLayoutPanel1.Controls.Add(this.rjButton1, 0, 4);
            this.tableLayoutPanel1.Controls.Add(this.numFlowChart, 0, 3);
            this.tableLayoutPanel1.Controls.Add(this.btnP1, 0, 2);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 13;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(452, 543);
            this.tableLayoutPanel1.TabIndex = 0;
            this.tableLayoutPanel1.Paint += new System.Windows.Forms.PaintEventHandler(this.tableLayoutPanel1_Paint);
            // 
            // tableLayoutPanel5
            // 
            this.tableLayoutPanel5.BackColor = System.Drawing.SystemColors.Control;
            this.tableLayoutPanel5.ColumnCount = 2;
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 70F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.tableLayoutPanel5.Controls.Add(this.btnClose, 1, 0);
            this.tableLayoutPanel5.Controls.Add(this.btnSave, 0, 0);
            this.tableLayoutPanel5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel5.Location = new System.Drawing.Point(3, 489);
            this.tableLayoutPanel5.Name = "tableLayoutPanel5";
            this.tableLayoutPanel5.RowCount = 1;
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel5.Size = new System.Drawing.Size(446, 51);
            this.tableLayoutPanel5.TabIndex = 112;
            // 
            // btnClose
            // 
            this.btnClose.AutoFont = true;
            this.btnClose.AutoFontHeightRatio = 0.75F;
            this.btnClose.AutoFontMax = 100F;
            this.btnClose.AutoFontMin = 6F;
            this.btnClose.AutoFontWidthRatio = 0.92F;
            this.btnClose.AutoImage = true;
            this.btnClose.AutoImageMaxRatio = 0.75F;
            this.btnClose.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnClose.AutoImageTint = true;
            this.btnClose.BackColor = System.Drawing.SystemColors.Control;
            this.btnClose.BackgroundColor = System.Drawing.SystemColors.Control;
            this.btnClose.BorderColor = System.Drawing.SystemColors.Control;
            this.btnClose.BorderRadius = 14;
            this.btnClose.BorderSize = 1;
            this.btnClose.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnClose.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnClose.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnClose.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnClose.Corner = BeeGlobal.Corner.Both;
            this.btnClose.DebounceResizeMs = 6;
            this.btnClose.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnClose.FlatAppearance.BorderSize = 0;
            this.btnClose.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnClose.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.07813F);
            this.btnClose.ForeColor = System.Drawing.Color.IndianRed;
            this.btnClose.Image = null;
            this.btnClose.ImageDisabled = null;
            this.btnClose.ImageHover = null;
            this.btnClose.ImageNormal = null;
            this.btnClose.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnClose.ImagePressed = null;
            this.btnClose.ImageTextSpacing = 6;
            this.btnClose.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnClose.ImageTintHover = System.Drawing.Color.Empty;
            this.btnClose.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnClose.ImageTintOpacity = 0.5F;
            this.btnClose.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnClose.IsCLick = false;
            this.btnClose.IsNotChange = false;
            this.btnClose.IsRect = false;
            this.btnClose.IsTouch = false;
            this.btnClose.IsUnGroup = false;
            this.btnClose.Location = new System.Drawing.Point(315, 3);
            this.btnClose.Multiline = false;
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new System.Drawing.Size(128, 45);
            this.btnClose.TabIndex = 72;
            this.btnClose.Text = "Close";
            this.btnClose.TextColor = System.Drawing.Color.IndianRed;
            this.btnClose.UseVisualStyleBackColor = false;
            // 
            // btnSave
            // 
            this.btnSave.AutoFont = true;
            this.btnSave.AutoFontHeightRatio = 0.75F;
            this.btnSave.AutoFontMax = 100F;
            this.btnSave.AutoFontMin = 6F;
            this.btnSave.AutoFontWidthRatio = 0.92F;
            this.btnSave.AutoImage = true;
            this.btnSave.AutoImageMaxRatio = 0.75F;
            this.btnSave.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnSave.AutoImageTint = true;
            this.btnSave.BackColor = System.Drawing.SystemColors.Control;
            this.btnSave.BackgroundColor = System.Drawing.SystemColors.Control;
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnSave.BorderColor = System.Drawing.SystemColors.Control;
            this.btnSave.BorderRadius = 20;
            this.btnSave.BorderSize = 1;
            this.btnSave.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnSave.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnSave.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnSave.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnSave.Corner = BeeGlobal.Corner.Both;
            this.btnSave.DebounceResizeMs = 6;
            this.btnSave.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnSave.FlatAppearance.BorderSize = 0;
            this.btnSave.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSave.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.07813F);
            this.btnSave.ForeColor = System.Drawing.Color.Black;
            this.btnSave.Image = null;
            this.btnSave.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSave.ImageDisabled = null;
            this.btnSave.ImageHover = null;
            this.btnSave.ImageNormal = null;
            this.btnSave.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnSave.ImagePressed = null;
            this.btnSave.ImageTextSpacing = 6;
            this.btnSave.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnSave.ImageTintHover = System.Drawing.Color.Empty;
            this.btnSave.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnSave.ImageTintOpacity = 0.5F;
            this.btnSave.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnSave.IsCLick = false;
            this.btnSave.IsNotChange = false;
            this.btnSave.IsRect = false;
            this.btnSave.IsTouch = false;
            this.btnSave.IsUnGroup = false;
            this.btnSave.Location = new System.Drawing.Point(3, 3);
            this.btnSave.Multiline = false;
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new System.Drawing.Size(306, 45);
            this.btnSave.TabIndex = 71;
            this.btnSave.Text = "Save Parameters";
            this.btnSave.TextColor = System.Drawing.Color.Black;
            this.btnSave.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnSave.UseVisualStyleBackColor = false;
            // 
            // adjustBarEx5
            // 
            this.adjustBarEx5.AutoRepeatAccelDeltaMs = -5;
            this.adjustBarEx5.AutoRepeatAccelerate = true;
            this.adjustBarEx5.AutoRepeatEnabled = true;
            this.adjustBarEx5.AutoRepeatInitialDelay = 400;
            this.adjustBarEx5.AutoRepeatInterval = 60;
            this.adjustBarEx5.AutoRepeatMinInterval = 20;
            this.adjustBarEx5.AutoShowTextbox = true;
            this.adjustBarEx5.AutoSizeTextbox = true;
            this.adjustBarEx5.BackColor = System.Drawing.Color.White;
            this.adjustBarEx5.BarLeftGap = 20;
            this.adjustBarEx5.BarRightGap = 6;
            this.adjustBarEx5.ChromeGap = 1;
            this.adjustBarEx5.ChromeWidthRatio = 0.14F;
            this.adjustBarEx5.ColorBorder = System.Drawing.Color.LightGray;
            this.adjustBarEx5.ColorFill = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(213)))), ((int)(((byte)(143)))));
            this.adjustBarEx5.ColorScale = System.Drawing.Color.LightGray;
            this.adjustBarEx5.ColorThumb = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.adjustBarEx5.ColorThumbBorder = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.adjustBarEx5.ColorTrack = System.Drawing.Color.LightGray;
            this.adjustBarEx5.Decimals = 0;
            this.adjustBarEx5.DisabledDesaturateMix = 0.3F;
            this.adjustBarEx5.DisabledDimFactor = 0.9F;
            this.adjustBarEx5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.adjustBarEx5.EdgePadding = 2;
            this.adjustBarEx5.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.adjustBarEx5.InnerPadding = new System.Windows.Forms.Padding(10, 6, 10, 6);
            this.adjustBarEx5.KeyboardStep = 1F;
            this.adjustBarEx5.Location = new System.Drawing.Point(5, 433);
            this.adjustBarEx5.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.adjustBarEx5.MatchTextboxFontToThumb = true;
            this.adjustBarEx5.Max = 100F;
            this.adjustBarEx5.MaxTextboxWidth = 0;
            this.adjustBarEx5.MaxThumb = 1000;
            this.adjustBarEx5.MaxTrackHeight = 1000;
            this.adjustBarEx5.Min = 1F;
            this.adjustBarEx5.MinChromeWidth = 64;
            this.adjustBarEx5.MinimumSize = new System.Drawing.Size(140, 36);
            this.adjustBarEx5.MinTextboxWidth = 32;
            this.adjustBarEx5.MinThumb = 30;
            this.adjustBarEx5.MinTrackHeight = 8;
            this.adjustBarEx5.Name = "adjustBarEx5";
            this.adjustBarEx5.Radius = 8;
            this.adjustBarEx5.ShowValueOnThumb = true;
            this.adjustBarEx5.Size = new System.Drawing.Size(442, 53);
            this.adjustBarEx5.SnapToStep = true;
            this.adjustBarEx5.StartWithTextboxHidden = true;
            this.adjustBarEx5.Step = 1F;
            this.adjustBarEx5.TabIndex = 111;
            this.adjustBarEx5.TextboxFontSize = 22F;
            this.adjustBarEx5.TextboxSidePadding = 10;
            this.adjustBarEx5.TextboxWidth = 600;
            this.adjustBarEx5.ThumbDiameterRatio = 1F;
            this.adjustBarEx5.ThumbValueBold = true;
            this.adjustBarEx5.ThumbValueFontScale = 1.5F;
            this.adjustBarEx5.ThumbValuePadding = 0;
            this.adjustBarEx5.TightEdges = true;
            this.adjustBarEx5.TrackHeightRatio = 0.45F;
            this.adjustBarEx5.TrackWidthRatio = 1F;
            this.adjustBarEx5.UnitText = "";
            this.adjustBarEx5.Value = 1F;
            this.adjustBarEx5.WheelStep = 1F;
            // 
            // rjButton5
            // 
            this.rjButton5.AutoFont = true;
            this.rjButton5.AutoFontHeightRatio = 0.75F;
            this.rjButton5.AutoFontMax = 100F;
            this.rjButton5.AutoFontMin = 11F;
            this.rjButton5.AutoFontWidthRatio = 0.92F;
            this.rjButton5.AutoImage = true;
            this.rjButton5.AutoImageMaxRatio = 0.75F;
            this.rjButton5.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.rjButton5.AutoImageTint = true;
            this.rjButton5.BackColor = System.Drawing.Color.White;
            this.rjButton5.BackgroundColor = System.Drawing.Color.White;
            this.rjButton5.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.rjButton5.BorderColor = System.Drawing.Color.White;
            this.rjButton5.BorderRadius = 10;
            this.rjButton5.BorderSize = 1;
            this.rjButton5.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.rjButton5.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.rjButton5.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.rjButton5.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.rjButton5.Corner = BeeGlobal.Corner.None;
            this.rjButton5.DebounceResizeMs = 6;
            this.rjButton5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rjButton5.FlatAppearance.BorderSize = 0;
            this.rjButton5.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.rjButton5.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Bold);
            this.rjButton5.ForeColor = System.Drawing.Color.White;
            this.rjButton5.Image = null;
            this.rjButton5.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.rjButton5.ImageDisabled = null;
            this.rjButton5.ImageHover = null;
            this.rjButton5.ImageNormal = null;
            this.rjButton5.ImagePadding = new System.Windows.Forms.Padding(1);
            this.rjButton5.ImagePressed = null;
            this.rjButton5.ImageTextSpacing = 6;
            this.rjButton5.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.rjButton5.ImageTintHover = System.Drawing.Color.Empty;
            this.rjButton5.ImageTintNormal = System.Drawing.Color.Empty;
            this.rjButton5.ImageTintOpacity = 0.5F;
            this.rjButton5.ImageTintPressed = System.Drawing.Color.Empty;
            this.rjButton5.IsCLick = true;
            this.rjButton5.IsNotChange = false;
            this.rjButton5.IsRect = false;
            this.rjButton5.IsTouch = true;
            this.rjButton5.IsUnGroup = true;
            this.rjButton5.Location = new System.Drawing.Point(5, 405);
            this.rjButton5.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.rjButton5.Multiline = false;
            this.rjButton5.Name = "rjButton5";
            this.rjButton5.Size = new System.Drawing.Size(442, 28);
            this.rjButton5.TabIndex = 110;
            this.rjButton5.Text = "Aspect Box";
            this.rjButton5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.rjButton5.TextColor = System.Drawing.Color.White;
            this.rjButton5.UseVisualStyleBackColor = false;
            // 
            // adjustBarEx4
            // 
            this.adjustBarEx4.AutoRepeatAccelDeltaMs = -5;
            this.adjustBarEx4.AutoRepeatAccelerate = true;
            this.adjustBarEx4.AutoRepeatEnabled = true;
            this.adjustBarEx4.AutoRepeatInitialDelay = 400;
            this.adjustBarEx4.AutoRepeatInterval = 60;
            this.adjustBarEx4.AutoRepeatMinInterval = 20;
            this.adjustBarEx4.AutoShowTextbox = true;
            this.adjustBarEx4.AutoSizeTextbox = true;
            this.adjustBarEx4.BackColor = System.Drawing.Color.White;
            this.adjustBarEx4.BarLeftGap = 20;
            this.adjustBarEx4.BarRightGap = 6;
            this.adjustBarEx4.ChromeGap = 1;
            this.adjustBarEx4.ChromeWidthRatio = 0.14F;
            this.adjustBarEx4.ColorBorder = System.Drawing.Color.LightGray;
            this.adjustBarEx4.ColorFill = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(213)))), ((int)(((byte)(143)))));
            this.adjustBarEx4.ColorScale = System.Drawing.Color.LightGray;
            this.adjustBarEx4.ColorThumb = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.adjustBarEx4.ColorThumbBorder = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.adjustBarEx4.ColorTrack = System.Drawing.Color.LightGray;
            this.adjustBarEx4.Decimals = 0;
            this.adjustBarEx4.DisabledDesaturateMix = 0.3F;
            this.adjustBarEx4.DisabledDimFactor = 0.9F;
            this.adjustBarEx4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.adjustBarEx4.EdgePadding = 2;
            this.adjustBarEx4.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.adjustBarEx4.InnerPadding = new System.Windows.Forms.Padding(10, 6, 10, 6);
            this.adjustBarEx4.KeyboardStep = 1F;
            this.adjustBarEx4.Location = new System.Drawing.Point(5, 352);
            this.adjustBarEx4.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.adjustBarEx4.MatchTextboxFontToThumb = true;
            this.adjustBarEx4.Max = 10F;
            this.adjustBarEx4.MaxTextboxWidth = 0;
            this.adjustBarEx4.MaxThumb = 1000;
            this.adjustBarEx4.MaxTrackHeight = 1000;
            this.adjustBarEx4.Min = 1F;
            this.adjustBarEx4.MinChromeWidth = 64;
            this.adjustBarEx4.MinimumSize = new System.Drawing.Size(140, 36);
            this.adjustBarEx4.MinTextboxWidth = 32;
            this.adjustBarEx4.MinThumb = 30;
            this.adjustBarEx4.MinTrackHeight = 8;
            this.adjustBarEx4.Name = "adjustBarEx4";
            this.adjustBarEx4.Radius = 8;
            this.adjustBarEx4.ShowValueOnThumb = true;
            this.adjustBarEx4.Size = new System.Drawing.Size(442, 53);
            this.adjustBarEx4.SnapToStep = true;
            this.adjustBarEx4.StartWithTextboxHidden = true;
            this.adjustBarEx4.Step = 1F;
            this.adjustBarEx4.TabIndex = 109;
            this.adjustBarEx4.TextboxFontSize = 22F;
            this.adjustBarEx4.TextboxSidePadding = 10;
            this.adjustBarEx4.TextboxWidth = 600;
            this.adjustBarEx4.ThumbDiameterRatio = 1F;
            this.adjustBarEx4.ThumbValueBold = true;
            this.adjustBarEx4.ThumbValueFontScale = 1.5F;
            this.adjustBarEx4.ThumbValuePadding = 0;
            this.adjustBarEx4.TightEdges = true;
            this.adjustBarEx4.TrackHeightRatio = 0.45F;
            this.adjustBarEx4.TrackWidthRatio = 1F;
            this.adjustBarEx4.UnitText = "";
            this.adjustBarEx4.Value = 1F;
            this.adjustBarEx4.WheelStep = 1F;
            // 
            // rjButton4
            // 
            this.rjButton4.AutoFont = true;
            this.rjButton4.AutoFontHeightRatio = 0.75F;
            this.rjButton4.AutoFontMax = 100F;
            this.rjButton4.AutoFontMin = 11F;
            this.rjButton4.AutoFontWidthRatio = 0.92F;
            this.rjButton4.AutoImage = true;
            this.rjButton4.AutoImageMaxRatio = 0.75F;
            this.rjButton4.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.rjButton4.AutoImageTint = true;
            this.rjButton4.BackColor = System.Drawing.Color.White;
            this.rjButton4.BackgroundColor = System.Drawing.Color.White;
            this.rjButton4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.rjButton4.BorderColor = System.Drawing.Color.White;
            this.rjButton4.BorderRadius = 10;
            this.rjButton4.BorderSize = 1;
            this.rjButton4.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.rjButton4.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.rjButton4.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.rjButton4.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.rjButton4.Corner = BeeGlobal.Corner.None;
            this.rjButton4.DebounceResizeMs = 6;
            this.rjButton4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rjButton4.FlatAppearance.BorderSize = 0;
            this.rjButton4.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.rjButton4.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Bold);
            this.rjButton4.ForeColor = System.Drawing.Color.White;
            this.rjButton4.Image = null;
            this.rjButton4.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.rjButton4.ImageDisabled = null;
            this.rjButton4.ImageHover = null;
            this.rjButton4.ImageNormal = null;
            this.rjButton4.ImagePadding = new System.Windows.Forms.Padding(1);
            this.rjButton4.ImagePressed = null;
            this.rjButton4.ImageTextSpacing = 6;
            this.rjButton4.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.rjButton4.ImageTintHover = System.Drawing.Color.Empty;
            this.rjButton4.ImageTintNormal = System.Drawing.Color.Empty;
            this.rjButton4.ImageTintOpacity = 0.5F;
            this.rjButton4.ImageTintPressed = System.Drawing.Color.Empty;
            this.rjButton4.IsCLick = true;
            this.rjButton4.IsNotChange = false;
            this.rjButton4.IsRect = false;
            this.rjButton4.IsTouch = true;
            this.rjButton4.IsUnGroup = true;
            this.rjButton4.Location = new System.Drawing.Point(5, 324);
            this.rjButton4.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.rjButton4.Multiline = false;
            this.rjButton4.Name = "rjButton4";
            this.rjButton4.Size = new System.Drawing.Size(442, 28);
            this.rjButton4.TabIndex = 108;
            this.rjButton4.Text = "Limit Y";
            this.rjButton4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.rjButton4.TextColor = System.Drawing.Color.White;
            this.rjButton4.UseVisualStyleBackColor = false;
            // 
            // adjustBarEx3
            // 
            this.adjustBarEx3.AutoRepeatAccelDeltaMs = -5;
            this.adjustBarEx3.AutoRepeatAccelerate = true;
            this.adjustBarEx3.AutoRepeatEnabled = true;
            this.adjustBarEx3.AutoRepeatInitialDelay = 400;
            this.adjustBarEx3.AutoRepeatInterval = 60;
            this.adjustBarEx3.AutoRepeatMinInterval = 20;
            this.adjustBarEx3.AutoShowTextbox = true;
            this.adjustBarEx3.AutoSizeTextbox = true;
            this.adjustBarEx3.BackColor = System.Drawing.Color.White;
            this.adjustBarEx3.BarLeftGap = 20;
            this.adjustBarEx3.BarRightGap = 6;
            this.adjustBarEx3.ChromeGap = 1;
            this.adjustBarEx3.ChromeWidthRatio = 0.14F;
            this.adjustBarEx3.ColorBorder = System.Drawing.Color.LightGray;
            this.adjustBarEx3.ColorFill = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(213)))), ((int)(((byte)(143)))));
            this.adjustBarEx3.ColorScale = System.Drawing.Color.LightGray;
            this.adjustBarEx3.ColorThumb = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.adjustBarEx3.ColorThumbBorder = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.adjustBarEx3.ColorTrack = System.Drawing.Color.LightGray;
            this.adjustBarEx3.Decimals = 0;
            this.adjustBarEx3.DisabledDesaturateMix = 0.3F;
            this.adjustBarEx3.DisabledDimFactor = 0.9F;
            this.adjustBarEx3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.adjustBarEx3.EdgePadding = 2;
            this.adjustBarEx3.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.adjustBarEx3.InnerPadding = new System.Windows.Forms.Padding(10, 6, 10, 6);
            this.adjustBarEx3.KeyboardStep = 1F;
            this.adjustBarEx3.Location = new System.Drawing.Point(5, 271);
            this.adjustBarEx3.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.adjustBarEx3.MatchTextboxFontToThumb = true;
            this.adjustBarEx3.Max = 10F;
            this.adjustBarEx3.MaxTextboxWidth = 0;
            this.adjustBarEx3.MaxThumb = 1000;
            this.adjustBarEx3.MaxTrackHeight = 1000;
            this.adjustBarEx3.Min = 1F;
            this.adjustBarEx3.MinChromeWidth = 64;
            this.adjustBarEx3.MinimumSize = new System.Drawing.Size(140, 36);
            this.adjustBarEx3.MinTextboxWidth = 32;
            this.adjustBarEx3.MinThumb = 30;
            this.adjustBarEx3.MinTrackHeight = 8;
            this.adjustBarEx3.Name = "adjustBarEx3";
            this.adjustBarEx3.Radius = 8;
            this.adjustBarEx3.ShowValueOnThumb = true;
            this.adjustBarEx3.Size = new System.Drawing.Size(442, 53);
            this.adjustBarEx3.SnapToStep = true;
            this.adjustBarEx3.StartWithTextboxHidden = true;
            this.adjustBarEx3.Step = 1F;
            this.adjustBarEx3.TabIndex = 107;
            this.adjustBarEx3.TextboxFontSize = 22F;
            this.adjustBarEx3.TextboxSidePadding = 10;
            this.adjustBarEx3.TextboxWidth = 600;
            this.adjustBarEx3.ThumbDiameterRatio = 1F;
            this.adjustBarEx3.ThumbValueBold = true;
            this.adjustBarEx3.ThumbValueFontScale = 1.5F;
            this.adjustBarEx3.ThumbValuePadding = 0;
            this.adjustBarEx3.TightEdges = true;
            this.adjustBarEx3.TrackHeightRatio = 0.45F;
            this.adjustBarEx3.TrackWidthRatio = 1F;
            this.adjustBarEx3.UnitText = "";
            this.adjustBarEx3.Value = 1F;
            this.adjustBarEx3.WheelStep = 1F;
            // 
            // rjButton3
            // 
            this.rjButton3.AutoFont = true;
            this.rjButton3.AutoFontHeightRatio = 0.75F;
            this.rjButton3.AutoFontMax = 100F;
            this.rjButton3.AutoFontMin = 11F;
            this.rjButton3.AutoFontWidthRatio = 0.92F;
            this.rjButton3.AutoImage = true;
            this.rjButton3.AutoImageMaxRatio = 0.75F;
            this.rjButton3.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.rjButton3.AutoImageTint = true;
            this.rjButton3.BackColor = System.Drawing.Color.White;
            this.rjButton3.BackgroundColor = System.Drawing.Color.White;
            this.rjButton3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.rjButton3.BorderColor = System.Drawing.Color.White;
            this.rjButton3.BorderRadius = 10;
            this.rjButton3.BorderSize = 1;
            this.rjButton3.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.rjButton3.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.rjButton3.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.rjButton3.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.rjButton3.Corner = BeeGlobal.Corner.None;
            this.rjButton3.DebounceResizeMs = 6;
            this.rjButton3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rjButton3.FlatAppearance.BorderSize = 0;
            this.rjButton3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.rjButton3.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Bold);
            this.rjButton3.ForeColor = System.Drawing.Color.White;
            this.rjButton3.Image = null;
            this.rjButton3.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.rjButton3.ImageDisabled = null;
            this.rjButton3.ImageHover = null;
            this.rjButton3.ImageNormal = null;
            this.rjButton3.ImagePadding = new System.Windows.Forms.Padding(1);
            this.rjButton3.ImagePressed = null;
            this.rjButton3.ImageTextSpacing = 6;
            this.rjButton3.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.rjButton3.ImageTintHover = System.Drawing.Color.Empty;
            this.rjButton3.ImageTintNormal = System.Drawing.Color.Empty;
            this.rjButton3.ImageTintOpacity = 0.5F;
            this.rjButton3.ImageTintPressed = System.Drawing.Color.Empty;
            this.rjButton3.IsCLick = true;
            this.rjButton3.IsNotChange = false;
            this.rjButton3.IsRect = false;
            this.rjButton3.IsTouch = true;
            this.rjButton3.IsUnGroup = true;
            this.rjButton3.Location = new System.Drawing.Point(5, 243);
            this.rjButton3.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.rjButton3.Multiline = false;
            this.rjButton3.Name = "rjButton3";
            this.rjButton3.Size = new System.Drawing.Size(442, 28);
            this.rjButton3.TabIndex = 106;
            this.rjButton3.Text = "Limit X";
            this.rjButton3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.rjButton3.TextColor = System.Drawing.Color.White;
            this.rjButton3.UseVisualStyleBackColor = false;
            // 
            // adjustBarEx2
            // 
            this.adjustBarEx2.AutoRepeatAccelDeltaMs = -5;
            this.adjustBarEx2.AutoRepeatAccelerate = true;
            this.adjustBarEx2.AutoRepeatEnabled = true;
            this.adjustBarEx2.AutoRepeatInitialDelay = 400;
            this.adjustBarEx2.AutoRepeatInterval = 60;
            this.adjustBarEx2.AutoRepeatMinInterval = 20;
            this.adjustBarEx2.AutoShowTextbox = true;
            this.adjustBarEx2.AutoSizeTextbox = true;
            this.adjustBarEx2.BackColor = System.Drawing.Color.White;
            this.adjustBarEx2.BarLeftGap = 20;
            this.adjustBarEx2.BarRightGap = 6;
            this.adjustBarEx2.ChromeGap = 1;
            this.adjustBarEx2.ChromeWidthRatio = 0.14F;
            this.adjustBarEx2.ColorBorder = System.Drawing.Color.LightGray;
            this.adjustBarEx2.ColorFill = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(213)))), ((int)(((byte)(143)))));
            this.adjustBarEx2.ColorScale = System.Drawing.Color.LightGray;
            this.adjustBarEx2.ColorThumb = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.adjustBarEx2.ColorThumbBorder = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.adjustBarEx2.ColorTrack = System.Drawing.Color.LightGray;
            this.adjustBarEx2.Decimals = 0;
            this.adjustBarEx2.DisabledDesaturateMix = 0.3F;
            this.adjustBarEx2.DisabledDimFactor = 0.9F;
            this.adjustBarEx2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.adjustBarEx2.EdgePadding = 2;
            this.adjustBarEx2.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.adjustBarEx2.InnerPadding = new System.Windows.Forms.Padding(10, 6, 10, 6);
            this.adjustBarEx2.KeyboardStep = 1F;
            this.adjustBarEx2.Location = new System.Drawing.Point(5, 28);
            this.adjustBarEx2.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.adjustBarEx2.MatchTextboxFontToThumb = true;
            this.adjustBarEx2.Max = 500F;
            this.adjustBarEx2.MaxTextboxWidth = 0;
            this.adjustBarEx2.MaxThumb = 1000;
            this.adjustBarEx2.MaxTrackHeight = 1000;
            this.adjustBarEx2.Min = 1F;
            this.adjustBarEx2.MinChromeWidth = 64;
            this.adjustBarEx2.MinimumSize = new System.Drawing.Size(140, 36);
            this.adjustBarEx2.MinTextboxWidth = 32;
            this.adjustBarEx2.MinThumb = 30;
            this.adjustBarEx2.MinTrackHeight = 8;
            this.adjustBarEx2.Name = "adjustBarEx2";
            this.adjustBarEx2.Radius = 8;
            this.adjustBarEx2.ShowValueOnThumb = true;
            this.adjustBarEx2.Size = new System.Drawing.Size(442, 53);
            this.adjustBarEx2.SnapToStep = true;
            this.adjustBarEx2.StartWithTextboxHidden = true;
            this.adjustBarEx2.Step = 1F;
            this.adjustBarEx2.TabIndex = 105;
            this.adjustBarEx2.TextboxFontSize = 22F;
            this.adjustBarEx2.TextboxSidePadding = 10;
            this.adjustBarEx2.TextboxWidth = 600;
            this.adjustBarEx2.ThumbDiameterRatio = 1F;
            this.adjustBarEx2.ThumbValueBold = true;
            this.adjustBarEx2.ThumbValueFontScale = 1.5F;
            this.adjustBarEx2.ThumbValuePadding = 0;
            this.adjustBarEx2.TightEdges = true;
            this.adjustBarEx2.TrackHeightRatio = 0.45F;
            this.adjustBarEx2.TrackWidthRatio = 1F;
            this.adjustBarEx2.UnitText = "";
            this.adjustBarEx2.Value = 1F;
            this.adjustBarEx2.WheelStep = 1F;
            // 
            // rjButton2
            // 
            this.rjButton2.AutoFont = true;
            this.rjButton2.AutoFontHeightRatio = 0.75F;
            this.rjButton2.AutoFontMax = 100F;
            this.rjButton2.AutoFontMin = 11F;
            this.rjButton2.AutoFontWidthRatio = 0.92F;
            this.rjButton2.AutoImage = true;
            this.rjButton2.AutoImageMaxRatio = 0.75F;
            this.rjButton2.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.rjButton2.AutoImageTint = true;
            this.rjButton2.BackColor = System.Drawing.Color.White;
            this.rjButton2.BackgroundColor = System.Drawing.Color.White;
            this.rjButton2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.rjButton2.BorderColor = System.Drawing.Color.White;
            this.rjButton2.BorderRadius = 10;
            this.rjButton2.BorderSize = 1;
            this.rjButton2.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.rjButton2.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.rjButton2.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.rjButton2.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.rjButton2.Corner = BeeGlobal.Corner.None;
            this.rjButton2.DebounceResizeMs = 6;
            this.rjButton2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rjButton2.FlatAppearance.BorderSize = 0;
            this.rjButton2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.rjButton2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Bold);
            this.rjButton2.ForeColor = System.Drawing.Color.White;
            this.rjButton2.Image = null;
            this.rjButton2.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.rjButton2.ImageDisabled = null;
            this.rjButton2.ImageHover = null;
            this.rjButton2.ImageNormal = null;
            this.rjButton2.ImagePadding = new System.Windows.Forms.Padding(1);
            this.rjButton2.ImagePressed = null;
            this.rjButton2.ImageTextSpacing = 6;
            this.rjButton2.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.rjButton2.ImageTintHover = System.Drawing.Color.Empty;
            this.rjButton2.ImageTintNormal = System.Drawing.Color.Empty;
            this.rjButton2.ImageTintOpacity = 0.5F;
            this.rjButton2.ImageTintPressed = System.Drawing.Color.Empty;
            this.rjButton2.IsCLick = true;
            this.rjButton2.IsNotChange = false;
            this.rjButton2.IsRect = false;
            this.rjButton2.IsTouch = true;
            this.rjButton2.IsUnGroup = true;
            this.rjButton2.Location = new System.Drawing.Point(5, 0);
            this.rjButton2.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.rjButton2.Multiline = false;
            this.rjButton2.Name = "rjButton2";
            this.rjButton2.Size = new System.Drawing.Size(442, 28);
            this.rjButton2.TabIndex = 104;
            this.rjButton2.Text = "Grab Delay (ms)";
            this.rjButton2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.rjButton2.TextColor = System.Drawing.Color.White;
            this.rjButton2.UseVisualStyleBackColor = false;
            // 
            // adjustBarEx1
            // 
            this.adjustBarEx1.AutoRepeatAccelDeltaMs = -5;
            this.adjustBarEx1.AutoRepeatAccelerate = true;
            this.adjustBarEx1.AutoRepeatEnabled = true;
            this.adjustBarEx1.AutoRepeatInitialDelay = 400;
            this.adjustBarEx1.AutoRepeatInterval = 60;
            this.adjustBarEx1.AutoRepeatMinInterval = 20;
            this.adjustBarEx1.AutoShowTextbox = true;
            this.adjustBarEx1.AutoSizeTextbox = true;
            this.adjustBarEx1.BackColor = System.Drawing.Color.White;
            this.adjustBarEx1.BarLeftGap = 20;
            this.adjustBarEx1.BarRightGap = 6;
            this.adjustBarEx1.ChromeGap = 1;
            this.adjustBarEx1.ChromeWidthRatio = 0.14F;
            this.adjustBarEx1.ColorBorder = System.Drawing.Color.LightGray;
            this.adjustBarEx1.ColorFill = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(213)))), ((int)(((byte)(143)))));
            this.adjustBarEx1.ColorScale = System.Drawing.Color.LightGray;
            this.adjustBarEx1.ColorThumb = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.adjustBarEx1.ColorThumbBorder = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.adjustBarEx1.ColorTrack = System.Drawing.Color.LightGray;
            this.adjustBarEx1.Decimals = 0;
            this.adjustBarEx1.DisabledDesaturateMix = 0.3F;
            this.adjustBarEx1.DisabledDimFactor = 0.9F;
            this.adjustBarEx1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.adjustBarEx1.EdgePadding = 2;
            this.adjustBarEx1.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.adjustBarEx1.InnerPadding = new System.Windows.Forms.Padding(10, 6, 10, 6);
            this.adjustBarEx1.KeyboardStep = 1F;
            this.adjustBarEx1.Location = new System.Drawing.Point(5, 190);
            this.adjustBarEx1.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.adjustBarEx1.MatchTextboxFontToThumb = true;
            this.adjustBarEx1.Max = 20F;
            this.adjustBarEx1.MaxTextboxWidth = 0;
            this.adjustBarEx1.MaxThumb = 1000;
            this.adjustBarEx1.MaxTrackHeight = 1000;
            this.adjustBarEx1.Min = 1F;
            this.adjustBarEx1.MinChromeWidth = 64;
            this.adjustBarEx1.MinimumSize = new System.Drawing.Size(140, 36);
            this.adjustBarEx1.MinTextboxWidth = 32;
            this.adjustBarEx1.MinThumb = 30;
            this.adjustBarEx1.MinTrackHeight = 8;
            this.adjustBarEx1.Name = "adjustBarEx1";
            this.adjustBarEx1.Radius = 8;
            this.adjustBarEx1.ShowValueOnThumb = true;
            this.adjustBarEx1.Size = new System.Drawing.Size(442, 53);
            this.adjustBarEx1.SnapToStep = true;
            this.adjustBarEx1.StartWithTextboxHidden = true;
            this.adjustBarEx1.Step = 1F;
            this.adjustBarEx1.TabIndex = 103;
            this.adjustBarEx1.TextboxFontSize = 22F;
            this.adjustBarEx1.TextboxSidePadding = 10;
            this.adjustBarEx1.TextboxWidth = 600;
            this.adjustBarEx1.ThumbDiameterRatio = 1F;
            this.adjustBarEx1.ThumbValueBold = true;
            this.adjustBarEx1.ThumbValueFontScale = 1.5F;
            this.adjustBarEx1.ThumbValuePadding = 0;
            this.adjustBarEx1.TightEdges = true;
            this.adjustBarEx1.TrackHeightRatio = 0.45F;
            this.adjustBarEx1.TrackWidthRatio = 1F;
            this.adjustBarEx1.UnitText = "";
            this.adjustBarEx1.Value = 1F;
            this.adjustBarEx1.WheelStep = 1F;
            // 
            // rjButton1
            // 
            this.rjButton1.AutoFont = true;
            this.rjButton1.AutoFontHeightRatio = 0.75F;
            this.rjButton1.AutoFontMax = 100F;
            this.rjButton1.AutoFontMin = 11F;
            this.rjButton1.AutoFontWidthRatio = 0.92F;
            this.rjButton1.AutoImage = true;
            this.rjButton1.AutoImageMaxRatio = 0.75F;
            this.rjButton1.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.rjButton1.AutoImageTint = true;
            this.rjButton1.BackColor = System.Drawing.Color.White;
            this.rjButton1.BackgroundColor = System.Drawing.Color.White;
            this.rjButton1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.rjButton1.BorderColor = System.Drawing.Color.White;
            this.rjButton1.BorderRadius = 10;
            this.rjButton1.BorderSize = 1;
            this.rjButton1.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.rjButton1.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.rjButton1.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.rjButton1.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.rjButton1.Corner = BeeGlobal.Corner.None;
            this.rjButton1.DebounceResizeMs = 6;
            this.rjButton1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rjButton1.FlatAppearance.BorderSize = 0;
            this.rjButton1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.rjButton1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Bold);
            this.rjButton1.ForeColor = System.Drawing.Color.White;
            this.rjButton1.Image = null;
            this.rjButton1.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.rjButton1.ImageDisabled = null;
            this.rjButton1.ImageHover = null;
            this.rjButton1.ImageNormal = null;
            this.rjButton1.ImagePadding = new System.Windows.Forms.Padding(1);
            this.rjButton1.ImagePressed = null;
            this.rjButton1.ImageTextSpacing = 6;
            this.rjButton1.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.rjButton1.ImageTintHover = System.Drawing.Color.Empty;
            this.rjButton1.ImageTintNormal = System.Drawing.Color.Empty;
            this.rjButton1.ImageTintOpacity = 0.5F;
            this.rjButton1.ImageTintPressed = System.Drawing.Color.Empty;
            this.rjButton1.IsCLick = true;
            this.rjButton1.IsNotChange = false;
            this.rjButton1.IsRect = false;
            this.rjButton1.IsTouch = true;
            this.rjButton1.IsUnGroup = true;
            this.rjButton1.Location = new System.Drawing.Point(5, 162);
            this.rjButton1.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.rjButton1.Multiline = false;
            this.rjButton1.Name = "rjButton1";
            this.rjButton1.Size = new System.Drawing.Size(442, 28);
            this.rjButton1.TabIndex = 102;
            this.rjButton1.Text = "Gain (ms)";
            this.rjButton1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.rjButton1.TextColor = System.Drawing.Color.White;
            this.rjButton1.UseVisualStyleBackColor = false;
            // 
            // numFlowChart
            // 
            this.numFlowChart.AutoRepeatAccelDeltaMs = -5;
            this.numFlowChart.AutoRepeatAccelerate = true;
            this.numFlowChart.AutoRepeatEnabled = true;
            this.numFlowChart.AutoRepeatInitialDelay = 400;
            this.numFlowChart.AutoRepeatInterval = 60;
            this.numFlowChart.AutoRepeatMinInterval = 20;
            this.numFlowChart.AutoShowTextbox = true;
            this.numFlowChart.AutoSizeTextbox = true;
            this.numFlowChart.BackColor = System.Drawing.Color.White;
            this.numFlowChart.BarLeftGap = 20;
            this.numFlowChart.BarRightGap = 6;
            this.numFlowChart.ChromeGap = 1;
            this.numFlowChart.ChromeWidthRatio = 0.14F;
            this.numFlowChart.ColorBorder = System.Drawing.Color.LightGray;
            this.numFlowChart.ColorFill = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(213)))), ((int)(((byte)(143)))));
            this.numFlowChart.ColorScale = System.Drawing.Color.LightGray;
            this.numFlowChart.ColorThumb = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.numFlowChart.ColorThumbBorder = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.numFlowChart.ColorTrack = System.Drawing.Color.LightGray;
            this.numFlowChart.Decimals = 0;
            this.numFlowChart.DisabledDesaturateMix = 0.3F;
            this.numFlowChart.DisabledDimFactor = 0.9F;
            this.numFlowChart.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numFlowChart.EdgePadding = 2;
            this.numFlowChart.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.numFlowChart.InnerPadding = new System.Windows.Forms.Padding(10, 6, 10, 6);
            this.numFlowChart.KeyboardStep = 1F;
            this.numFlowChart.Location = new System.Drawing.Point(5, 109);
            this.numFlowChart.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.numFlowChart.MatchTextboxFontToThumb = true;
            this.numFlowChart.Max = 3000F;
            this.numFlowChart.MaxTextboxWidth = 0;
            this.numFlowChart.MaxThumb = 1000;
            this.numFlowChart.MaxTrackHeight = 1000;
            this.numFlowChart.Min = 1F;
            this.numFlowChart.MinChromeWidth = 64;
            this.numFlowChart.MinimumSize = new System.Drawing.Size(140, 36);
            this.numFlowChart.MinTextboxWidth = 32;
            this.numFlowChart.MinThumb = 30;
            this.numFlowChart.MinTrackHeight = 8;
            this.numFlowChart.Name = "numFlowChart";
            this.numFlowChart.Radius = 8;
            this.numFlowChart.ShowValueOnThumb = true;
            this.numFlowChart.Size = new System.Drawing.Size(442, 53);
            this.numFlowChart.SnapToStep = true;
            this.numFlowChart.StartWithTextboxHidden = true;
            this.numFlowChart.Step = 1F;
            this.numFlowChart.TabIndex = 101;
            this.numFlowChart.TextboxFontSize = 22F;
            this.numFlowChart.TextboxSidePadding = 10;
            this.numFlowChart.TextboxWidth = 600;
            this.numFlowChart.ThumbDiameterRatio = 1F;
            this.numFlowChart.ThumbValueBold = true;
            this.numFlowChart.ThumbValueFontScale = 1.5F;
            this.numFlowChart.ThumbValuePadding = 0;
            this.numFlowChart.TightEdges = true;
            this.numFlowChart.TrackHeightRatio = 0.45F;
            this.numFlowChart.TrackWidthRatio = 1F;
            this.numFlowChart.UnitText = "";
            this.numFlowChart.Value = 1F;
            this.numFlowChart.WheelStep = 1F;
            // 
            // btnP1
            // 
            this.btnP1.AutoFont = true;
            this.btnP1.AutoFontHeightRatio = 0.75F;
            this.btnP1.AutoFontMax = 100F;
            this.btnP1.AutoFontMin = 11F;
            this.btnP1.AutoFontWidthRatio = 0.92F;
            this.btnP1.AutoImage = true;
            this.btnP1.AutoImageMaxRatio = 0.75F;
            this.btnP1.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnP1.AutoImageTint = true;
            this.btnP1.BackColor = System.Drawing.Color.White;
            this.btnP1.BackgroundColor = System.Drawing.Color.White;
            this.btnP1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnP1.BorderColor = System.Drawing.Color.White;
            this.btnP1.BorderRadius = 10;
            this.btnP1.BorderSize = 1;
            this.btnP1.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnP1.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnP1.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnP1.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnP1.Corner = BeeGlobal.Corner.None;
            this.btnP1.DebounceResizeMs = 6;
            this.btnP1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnP1.FlatAppearance.BorderSize = 0;
            this.btnP1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnP1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Bold);
            this.btnP1.ForeColor = System.Drawing.Color.White;
            this.btnP1.Image = null;
            this.btnP1.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnP1.ImageDisabled = null;
            this.btnP1.ImageHover = null;
            this.btnP1.ImageNormal = null;
            this.btnP1.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnP1.ImagePressed = null;
            this.btnP1.ImageTextSpacing = 6;
            this.btnP1.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnP1.ImageTintHover = System.Drawing.Color.Empty;
            this.btnP1.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnP1.ImageTintOpacity = 0.5F;
            this.btnP1.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnP1.IsCLick = true;
            this.btnP1.IsNotChange = false;
            this.btnP1.IsRect = false;
            this.btnP1.IsTouch = true;
            this.btnP1.IsUnGroup = true;
            this.btnP1.Location = new System.Drawing.Point(5, 81);
            this.btnP1.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.btnP1.Multiline = false;
            this.btnP1.Name = "btnP1";
            this.btnP1.Size = new System.Drawing.Size(442, 28);
            this.btnP1.TabIndex = 100;
            this.btnP1.Text = "Exposure Time (ms)";
            this.btnP1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnP1.TextColor = System.Drawing.Color.White;
            this.btnP1.UseVisualStyleBackColor = false;
            // 
            // QuickSetting
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(452, 543);
            this.Controls.Add(this.tableLayoutPanel1);
            this.DoubleBuffered = true;
            this.Name = "QuickSetting";
            this.Text = "QuickSetting";
            this.Load += new System.EventHandler(this.QuickSetting_Load);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel5.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private BeeInterface.RJButton btnP1;
        private BeeInterface.AdjustBarEx adjustBarEx1;
        private BeeInterface.RJButton rjButton1;
        private BeeInterface.AdjustBarEx numFlowChart;
        private BeeInterface.AdjustBarEx adjustBarEx2;
        private BeeInterface.RJButton rjButton2;
        private BeeInterface.AdjustBarEx adjustBarEx4;
        private BeeInterface.RJButton rjButton4;
        private BeeInterface.AdjustBarEx adjustBarEx3;
        private BeeInterface.RJButton rjButton3;
        private BeeInterface.AdjustBarEx adjustBarEx5;
        private BeeInterface.RJButton rjButton5;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel5;
        private BeeInterface.RJButton btnClose;
        private BeeInterface.RJButton btnSave;
    }
}