using BeeCore;
using BeeGlobal;

namespace BeeInterface
{
    partial class ToolBarcode
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ToolBarcode));
            this.tabControl2 = new System.Windows.Forms.TabControl();
            this.tabP1 = new System.Windows.Forms.TabPage();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel7 = new System.Windows.Forms.TableLayoutPanel();
            this.btnChooseOCR = new BeeInterface.RJButton();
            this.btnScanOCR = new BeeInterface.RJButton();
            this.AdjOffSetArea = new BeeInterface.AdjustBarEx();
            this.label2 = new System.Windows.Forms.Label();
            this.lay3 = new System.Windows.Forms.TableLayoutPanel();
            this.imgTemp = new System.Windows.Forms.PictureBox();
            this.tableLayoutPanel4 = new System.Windows.Forms.TableLayoutPanel();
            this.label4 = new System.Windows.Forms.Label();
            this.btnBlack = new BeeInterface.RJButton();
            this.btnWhite = new BeeInterface.RJButton();
            this.tableLayoutPanel6 = new System.Windows.Forms.TableLayoutPanel();
            this.btnNewShape = new BeeInterface.RJButton();
            this.tableLayoutPanel5 = new System.Windows.Forms.TableLayoutPanel();
            this.btnPolygon = new BeeInterface.RJButton();
            this.btnHexagon = new BeeInterface.RJButton();
            this.btnElip = new BeeInterface.RJButton();
            this.btnRect = new BeeInterface.RJButton();
            this.btnNone = new BeeInterface.RJButton();
            this.label3 = new System.Windows.Forms.Label();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.btnMask = new BeeInterface.RJButton();
            this.btnCrop = new BeeInterface.RJButton();
            this.btnArea = new BeeInterface.RJButton();
            this.label1 = new System.Windows.Forms.Label();
            this.trackScore = new BeeInterface.AdjustBarEx();
            this.label8 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.btnCropFull = new BeeInterface.RJButton();
            this.btnCropHalt = new BeeInterface.RJButton();
            this.pInspect = new System.Windows.Forms.Panel();
            this.btnTest = new BeeInterface.RJButton();
            this.oK_Cancel1 = new BeeInterface.GroupControl.OK_Cancel();
            this.tabControl2.SuspendLayout();
            this.tabP1.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.tableLayoutPanel7.SuspendLayout();
            this.lay3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.imgTemp)).BeginInit();
            this.tableLayoutPanel4.SuspendLayout();
            this.tableLayoutPanel6.SuspendLayout();
            this.tableLayoutPanel5.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.pInspect.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabControl2
            // 
            this.tabControl2.Controls.Add(this.tabP1);
            this.tabControl2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl2.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tabControl2.Location = new System.Drawing.Point(0, 0);
            this.tabControl2.Name = "tabControl2";
            this.tabControl2.SelectedIndex = 0;
            this.tabControl2.Size = new System.Drawing.Size(468, 777);
            this.tabControl2.TabIndex = 17;
            // 
            // tabP1
            // 
            this.tabP1.BackColor = System.Drawing.SystemColors.Control;
            this.tabP1.Controls.Add(this.tableLayoutPanel1);
            this.tabP1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tabP1.Location = new System.Drawing.Point(4, 38);
            this.tabP1.Name = "tabP1";
            this.tabP1.Padding = new System.Windows.Forms.Padding(3);
            this.tabP1.Size = new System.Drawing.Size(460, 735);
            this.tabP1.TabIndex = 0;
            this.tabP1.Text = "Basic";
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.AutoScroll = true;
            this.tableLayoutPanel1.BackColor = System.Drawing.SystemColors.Control;
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel7, 0, 9);
            this.tableLayoutPanel1.Controls.Add(this.AdjOffSetArea, 0, 12);
            this.tableLayoutPanel1.Controls.Add(this.label2, 0, 11);
            this.tableLayoutPanel1.Controls.Add(this.lay3, 0, 10);
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel4, 0, 7);
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel6, 0, 6);
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel5, 0, 5);
            this.tableLayoutPanel1.Controls.Add(this.label3, 0, 4);
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel3, 0, 3);
            this.tableLayoutPanel1.Controls.Add(this.label1, 0, 2);
            this.tableLayoutPanel1.Controls.Add(this.trackScore, 0, 15);
            this.tableLayoutPanel1.Controls.Add(this.label8, 0, 14);
            this.tableLayoutPanel1.Controls.Add(this.label7, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel2, 0, 1);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tableLayoutPanel1.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel1.Margin = new System.Windows.Forms.Padding(3, 3, 3, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.Padding = new System.Windows.Forms.Padding(1, 0, 1, 0);
            this.tableLayoutPanel1.RowCount = 18;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 70F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(454, 729);
            this.tableLayoutPanel1.TabIndex = 1;
            // 
            // tableLayoutPanel7
            // 
            this.tableLayoutPanel7.BackColor = System.Drawing.Color.White;
            this.tableLayoutPanel7.ColumnCount = 4;
            this.tableLayoutPanel7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel7.Controls.Add(this.btnChooseOCR, 3, 0);
            this.tableLayoutPanel7.Controls.Add(this.btnScanOCR, 2, 0);
            this.tableLayoutPanel7.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel7.Location = new System.Drawing.Point(6, 355);
            this.tableLayoutPanel7.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.tableLayoutPanel7.Name = "tableLayoutPanel7";
            this.tableLayoutPanel7.Padding = new System.Windows.Forms.Padding(5);
            this.tableLayoutPanel7.RowCount = 1;
            this.tableLayoutPanel7.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel7.Size = new System.Drawing.Size(430, 80);
            this.tableLayoutPanel7.TabIndex = 92;
            // 
            // btnChooseOCR
            // 
            this.btnChooseOCR.AutoFont = false;
            this.btnChooseOCR.AutoFontHeightRatio = 0.75F;
            this.btnChooseOCR.AutoFontMax = 100F;
            this.btnChooseOCR.AutoFontMin = 6F;
            this.btnChooseOCR.AutoFontWidthRatio = 0.92F;
            this.btnChooseOCR.AutoImage = true;
            this.btnChooseOCR.AutoImageMaxRatio = 0.75F;
            this.btnChooseOCR.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnChooseOCR.AutoImageTint = true;
            this.btnChooseOCR.BackColor = System.Drawing.SystemColors.Control;
            this.btnChooseOCR.BackgroundColor = System.Drawing.SystemColors.Control;
            this.btnChooseOCR.BorderColor = System.Drawing.SystemColors.Control;
            this.btnChooseOCR.BorderRadius = 10;
            this.btnChooseOCR.BorderSize = 1;
            this.btnChooseOCR.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnChooseOCR.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnChooseOCR.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnChooseOCR.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnChooseOCR.Corner = BeeGlobal.Corner.Both;
            this.btnChooseOCR.DebounceResizeMs = 16;
            this.btnChooseOCR.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnChooseOCR.FlatAppearance.BorderSize = 0;
            this.btnChooseOCR.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnChooseOCR.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnChooseOCR.ForeColor = System.Drawing.Color.Black;
            this.btnChooseOCR.Image = null;
            this.btnChooseOCR.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChooseOCR.ImageDisabled = null;
            this.btnChooseOCR.ImageHover = null;
            this.btnChooseOCR.ImageNormal = null;
            this.btnChooseOCR.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnChooseOCR.ImagePressed = null;
            this.btnChooseOCR.ImageTextSpacing = 6;
            this.btnChooseOCR.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnChooseOCR.ImageTintHover = System.Drawing.Color.Empty;
            this.btnChooseOCR.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnChooseOCR.ImageTintOpacity = 0.5F;
            this.btnChooseOCR.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnChooseOCR.IsCLick = false;
            this.btnChooseOCR.IsNotChange = false;
            this.btnChooseOCR.IsRect = false;
            this.btnChooseOCR.IsUnGroup = true;
            this.btnChooseOCR.Location = new System.Drawing.Point(225, 5);
            this.btnChooseOCR.Margin = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnChooseOCR.Multiline = false;
            this.btnChooseOCR.Name = "btnChooseOCR";
            this.btnChooseOCR.Size = new System.Drawing.Size(200, 70);
            this.btnChooseOCR.TabIndex = 88;
            this.btnChooseOCR.Text = "Choose QRCODE";
            this.btnChooseOCR.TextColor = System.Drawing.Color.Black;
            this.btnChooseOCR.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnChooseOCR.UseVisualStyleBackColor = false;
            this.btnChooseOCR.Click += new System.EventHandler(this.rjButton2_Click);
            // 
            // btnScanOCR
            // 
            this.btnScanOCR.AutoFont = false;
            this.btnScanOCR.AutoFontHeightRatio = 0.75F;
            this.btnScanOCR.AutoFontMax = 100F;
            this.btnScanOCR.AutoFontMin = 6F;
            this.btnScanOCR.AutoFontWidthRatio = 0.92F;
            this.btnScanOCR.AutoImage = true;
            this.btnScanOCR.AutoImageMaxRatio = 0.75F;
            this.btnScanOCR.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnScanOCR.AutoImageTint = true;
            this.btnScanOCR.BackColor = System.Drawing.SystemColors.Control;
            this.btnScanOCR.BackgroundColor = System.Drawing.SystemColors.Control;
            this.btnScanOCR.BorderColor = System.Drawing.SystemColors.Control;
            this.btnScanOCR.BorderRadius = 10;
            this.btnScanOCR.BorderSize = 1;
            this.btnScanOCR.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnScanOCR.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnScanOCR.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnScanOCR.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnScanOCR.Corner = BeeGlobal.Corner.Both;
            this.btnScanOCR.DebounceResizeMs = 16;
            this.btnScanOCR.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnScanOCR.FlatAppearance.BorderSize = 0;
            this.btnScanOCR.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnScanOCR.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnScanOCR.ForeColor = System.Drawing.Color.Black;
            this.btnScanOCR.Image = null;
            this.btnScanOCR.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnScanOCR.ImageDisabled = null;
            this.btnScanOCR.ImageHover = null;
            this.btnScanOCR.ImageNormal = null;
            this.btnScanOCR.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnScanOCR.ImagePressed = null;
            this.btnScanOCR.ImageTextSpacing = 6;
            this.btnScanOCR.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnScanOCR.ImageTintHover = System.Drawing.Color.Empty;
            this.btnScanOCR.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnScanOCR.ImageTintOpacity = 0.5F;
            this.btnScanOCR.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnScanOCR.IsCLick = false;
            this.btnScanOCR.IsNotChange = true;
            this.btnScanOCR.IsRect = false;
            this.btnScanOCR.IsUnGroup = true;
            this.btnScanOCR.Location = new System.Drawing.Point(5, 5);
            this.btnScanOCR.Margin = new System.Windows.Forms.Padding(0, 0, 10, 0);
            this.btnScanOCR.Multiline = false;
            this.btnScanOCR.Name = "btnScanOCR";
            this.btnScanOCR.Size = new System.Drawing.Size(200, 70);
            this.btnScanOCR.TabIndex = 87;
            this.btnScanOCR.Text = "Scan QRCODE";
            this.btnScanOCR.TextColor = System.Drawing.Color.Black;
            this.btnScanOCR.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnScanOCR.UseVisualStyleBackColor = false;
            this.btnScanOCR.Click += new System.EventHandler(this.btnScanOCR_Click);
            // 
            // AdjOffSetArea
            // 
            this.AdjOffSetArea.AutoRepeatAccelDeltaMs = -5;
            this.AdjOffSetArea.AutoRepeatAccelerate = true;
            this.AdjOffSetArea.AutoRepeatEnabled = true;
            this.AdjOffSetArea.AutoRepeatInitialDelay = 400;
            this.AdjOffSetArea.AutoRepeatInterval = 60;
            this.AdjOffSetArea.AutoRepeatMinInterval = 20;
            this.AdjOffSetArea.AutoShowTextbox = true;
            this.AdjOffSetArea.AutoSizeTextbox = true;
            this.AdjOffSetArea.BackColor = System.Drawing.Color.White;
            this.AdjOffSetArea.BarLeftGap = 20;
            this.AdjOffSetArea.BarRightGap = 6;
            this.AdjOffSetArea.ChromeGap = 1;
            this.AdjOffSetArea.ChromeWidthRatio = 0.14F;
            this.AdjOffSetArea.ColorBorder = System.Drawing.Color.LightGray;
            this.AdjOffSetArea.ColorFill = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(213)))), ((int)(((byte)(143)))));
            this.AdjOffSetArea.ColorScale = System.Drawing.Color.LightGray;
            this.AdjOffSetArea.ColorThumb = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.AdjOffSetArea.ColorThumbBorder = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.AdjOffSetArea.ColorTrack = System.Drawing.Color.LightGray;
            this.AdjOffSetArea.Decimals = 0;
            this.AdjOffSetArea.DisabledDesaturateMix = 0.3F;
            this.AdjOffSetArea.DisabledDimFactor = 0.9F;
            this.AdjOffSetArea.Dock = System.Windows.Forms.DockStyle.Fill;
            this.AdjOffSetArea.EdgePadding = 2;
            this.AdjOffSetArea.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.AdjOffSetArea.InnerPadding = new System.Windows.Forms.Padding(10, 6, 10, 6);
            this.AdjOffSetArea.KeyboardStep = 1F;
            this.AdjOffSetArea.Location = new System.Drawing.Point(6, 677);
            this.AdjOffSetArea.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.AdjOffSetArea.MatchTextboxFontToThumb = true;
            this.AdjOffSetArea.Max = 100F;
            this.AdjOffSetArea.MaxTextboxWidth = 0;
            this.AdjOffSetArea.MaxThumb = 1000;
            this.AdjOffSetArea.MaxTrackHeight = 1000;
            this.AdjOffSetArea.Min = 0F;
            this.AdjOffSetArea.MinChromeWidth = 64;
            this.AdjOffSetArea.MinimumSize = new System.Drawing.Size(140, 36);
            this.AdjOffSetArea.MinTextboxWidth = 32;
            this.AdjOffSetArea.MinThumb = 30;
            this.AdjOffSetArea.MinTrackHeight = 8;
            this.AdjOffSetArea.Name = "AdjOffSetArea";
            this.AdjOffSetArea.Radius = 8;
            this.AdjOffSetArea.ShowValueOnThumb = true;
            this.AdjOffSetArea.Size = new System.Drawing.Size(430, 53);
            this.AdjOffSetArea.SnapToStep = true;
            this.AdjOffSetArea.StartWithTextboxHidden = true;
            this.AdjOffSetArea.Step = 1F;
            this.AdjOffSetArea.TabIndex = 91;
            this.AdjOffSetArea.TextboxFontSize = 22F;
            this.AdjOffSetArea.TextboxSidePadding = 10;
            this.AdjOffSetArea.TextboxWidth = 600;
            this.AdjOffSetArea.ThumbDiameterRatio = 2F;
            this.AdjOffSetArea.ThumbValueBold = true;
            this.AdjOffSetArea.ThumbValueFontScale = 1.5F;
            this.AdjOffSetArea.ThumbValuePadding = 0;
            this.AdjOffSetArea.TightEdges = true;
            this.AdjOffSetArea.TrackHeightRatio = 0.45F;
            this.AdjOffSetArea.TrackWidthRatio = 1F;
            this.AdjOffSetArea.UnitText = "";
            this.AdjOffSetArea.Value = 0F;
            this.AdjOffSetArea.WheelStep = 1F;
            this.AdjOffSetArea.ValueChanged += new System.Action<float>(this.AdjOffSetArea_ValueChanged);
            // 
            // label2
            // 
            this.label2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            this.label2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.Transparent;
            this.label2.Location = new System.Drawing.Point(6, 645);
            this.label2.Margin = new System.Windows.Forms.Padding(5, 10, 5, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(430, 32);
            this.label2.TabIndex = 90;
            this.label2.Text = "Offset Area Check";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // lay3
            // 
            this.lay3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(250)))), ((int)(((byte)(250)))));
            this.lay3.ColumnCount = 1;
            this.lay3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.lay3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.lay3.Controls.Add(this.imgTemp, 0, 0);
            this.lay3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lay3.Location = new System.Drawing.Point(6, 435);
            this.lay3.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.lay3.Name = "lay3";
            this.lay3.Padding = new System.Windows.Forms.Padding(5);
            this.lay3.RowCount = 1;
            this.lay3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.lay3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 190F));
            this.lay3.Size = new System.Drawing.Size(430, 200);
            this.lay3.TabIndex = 89;
            // 
            // imgTemp
            // 
            this.imgTemp.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.imgTemp.Dock = System.Windows.Forms.DockStyle.Fill;
            this.imgTemp.Location = new System.Drawing.Point(10, 10);
            this.imgTemp.Margin = new System.Windows.Forms.Padding(5);
            this.imgTemp.Name = "imgTemp";
            this.imgTemp.Size = new System.Drawing.Size(410, 180);
            this.imgTemp.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.imgTemp.TabIndex = 31;
            this.imgTemp.TabStop = false;
            // 
            // tableLayoutPanel4
            // 
            this.tableLayoutPanel4.BackColor = System.Drawing.Color.White;
            this.tableLayoutPanel4.ColumnCount = 4;
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel4.Controls.Add(this.label4, 1, 0);
            this.tableLayoutPanel4.Controls.Add(this.btnBlack, 3, 0);
            this.tableLayoutPanel4.Controls.Add(this.btnWhite, 2, 0);
            this.tableLayoutPanel4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel4.Location = new System.Drawing.Point(6, 307);
            this.tableLayoutPanel4.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.tableLayoutPanel4.Name = "tableLayoutPanel4";
            this.tableLayoutPanel4.Padding = new System.Windows.Forms.Padding(5);
            this.tableLayoutPanel4.RowCount = 1;
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel4.Size = new System.Drawing.Size(430, 48);
            this.tableLayoutPanel4.TabIndex = 86;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(5, 5);
            this.label4.Margin = new System.Windows.Forms.Padding(0, 0, 3, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(86, 38);
            this.label4.TabIndex = 59;
            this.label4.Text = "Color Mask";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // btnBlack
            // 
            this.btnBlack.AutoFont = true;
            this.btnBlack.AutoFontHeightRatio = 0.75F;
            this.btnBlack.AutoFontMax = 100F;
            this.btnBlack.AutoFontMin = 6F;
            this.btnBlack.AutoFontWidthRatio = 0.92F;
            this.btnBlack.AutoImage = true;
            this.btnBlack.AutoImageMaxRatio = 0.75F;
            this.btnBlack.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnBlack.AutoImageTint = true;
            this.btnBlack.BackColor = System.Drawing.Color.White;
            this.btnBlack.BackgroundColor = System.Drawing.Color.White;
            this.btnBlack.BorderColor = System.Drawing.Color.White;
            this.btnBlack.BorderRadius = 10;
            this.btnBlack.BorderSize = 1;
            this.btnBlack.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnBlack.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnBlack.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnBlack.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnBlack.Corner = BeeGlobal.Corner.Right;
            this.btnBlack.DebounceResizeMs = 16;
            this.btnBlack.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnBlack.FlatAppearance.BorderSize = 0;
            this.btnBlack.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBlack.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.14063F);
            this.btnBlack.ForeColor = System.Drawing.Color.Black;
            this.btnBlack.Image = null;
            this.btnBlack.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBlack.ImageDisabled = null;
            this.btnBlack.ImageHover = null;
            this.btnBlack.ImageNormal = null;
            this.btnBlack.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnBlack.ImagePressed = null;
            this.btnBlack.ImageTextSpacing = 6;
            this.btnBlack.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnBlack.ImageTintHover = System.Drawing.Color.Empty;
            this.btnBlack.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnBlack.ImageTintOpacity = 0.5F;
            this.btnBlack.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnBlack.IsCLick = false;
            this.btnBlack.IsNotChange = false;
            this.btnBlack.IsRect = false;
            this.btnBlack.IsUnGroup = false;
            this.btnBlack.Location = new System.Drawing.Point(259, 5);
            this.btnBlack.Margin = new System.Windows.Forms.Padding(0);
            this.btnBlack.Multiline = false;
            this.btnBlack.Name = "btnBlack";
            this.btnBlack.Size = new System.Drawing.Size(166, 38);
            this.btnBlack.TabIndex = 5;
            this.btnBlack.Text = "Black";
            this.btnBlack.TextColor = System.Drawing.Color.Black;
            this.btnBlack.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnBlack.UseVisualStyleBackColor = false;
            this.btnBlack.Click += new System.EventHandler(this.btnBlack_Click);
            // 
            // btnWhite
            // 
            this.btnWhite.AutoFont = true;
            this.btnWhite.AutoFontHeightRatio = 0.75F;
            this.btnWhite.AutoFontMax = 100F;
            this.btnWhite.AutoFontMin = 6F;
            this.btnWhite.AutoFontWidthRatio = 0.92F;
            this.btnWhite.AutoImage = true;
            this.btnWhite.AutoImageMaxRatio = 0.75F;
            this.btnWhite.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnWhite.AutoImageTint = true;
            this.btnWhite.BackColor = System.Drawing.Color.White;
            this.btnWhite.BackgroundColor = System.Drawing.Color.White;
            this.btnWhite.BorderColor = System.Drawing.Color.White;
            this.btnWhite.BorderRadius = 10;
            this.btnWhite.BorderSize = 1;
            this.btnWhite.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnWhite.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnWhite.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnWhite.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnWhite.Corner = BeeGlobal.Corner.Left;
            this.btnWhite.DebounceResizeMs = 16;
            this.btnWhite.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnWhite.FlatAppearance.BorderSize = 0;
            this.btnWhite.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnWhite.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.14063F);
            this.btnWhite.ForeColor = System.Drawing.Color.Black;
            this.btnWhite.Image = null;
            this.btnWhite.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnWhite.ImageDisabled = null;
            this.btnWhite.ImageHover = null;
            this.btnWhite.ImageNormal = null;
            this.btnWhite.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnWhite.ImagePressed = null;
            this.btnWhite.ImageTextSpacing = 6;
            this.btnWhite.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnWhite.ImageTintHover = System.Drawing.Color.Empty;
            this.btnWhite.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnWhite.ImageTintOpacity = 0.5F;
            this.btnWhite.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnWhite.IsCLick = false;
            this.btnWhite.IsNotChange = false;
            this.btnWhite.IsRect = false;
            this.btnWhite.IsUnGroup = false;
            this.btnWhite.Location = new System.Drawing.Point(94, 5);
            this.btnWhite.Margin = new System.Windows.Forms.Padding(0);
            this.btnWhite.Multiline = false;
            this.btnWhite.Name = "btnWhite";
            this.btnWhite.Size = new System.Drawing.Size(165, 38);
            this.btnWhite.TabIndex = 6;
            this.btnWhite.Text = "Whilte";
            this.btnWhite.TextColor = System.Drawing.Color.Black;
            this.btnWhite.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnWhite.UseVisualStyleBackColor = false;
            this.btnWhite.Click += new System.EventHandler(this.btnWhite_Click);
            // 
            // tableLayoutPanel6
            // 
            this.tableLayoutPanel6.BackColor = System.Drawing.Color.White;
            this.tableLayoutPanel6.ColumnCount = 2;
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel6.Controls.Add(this.btnNewShape, 1, 0);
            this.tableLayoutPanel6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel6.Location = new System.Drawing.Point(6, 262);
            this.tableLayoutPanel6.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.tableLayoutPanel6.Name = "tableLayoutPanel6";
            this.tableLayoutPanel6.Padding = new System.Windows.Forms.Padding(5);
            this.tableLayoutPanel6.RowCount = 1;
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel6.Size = new System.Drawing.Size(430, 45);
            this.tableLayoutPanel6.TabIndex = 85;
            // 
            // btnNewShape
            // 
            this.btnNewShape.AutoFont = true;
            this.btnNewShape.AutoFontHeightRatio = 0.75F;
            this.btnNewShape.AutoFontMax = 100F;
            this.btnNewShape.AutoFontMin = 6F;
            this.btnNewShape.AutoFontWidthRatio = 0.92F;
            this.btnNewShape.AutoImage = true;
            this.btnNewShape.AutoImageMaxRatio = 0.75F;
            this.btnNewShape.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnNewShape.AutoImageTint = true;
            this.btnNewShape.BackColor = System.Drawing.Color.White;
            this.btnNewShape.BackgroundColor = System.Drawing.Color.White;
            this.btnNewShape.BorderColor = System.Drawing.Color.White;
            this.btnNewShape.BorderRadius = 10;
            this.btnNewShape.BorderSize = 1;
            this.btnNewShape.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnNewShape.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnNewShape.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnNewShape.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnNewShape.Corner = BeeGlobal.Corner.Both;
            this.btnNewShape.DebounceResizeMs = 16;
            this.btnNewShape.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnNewShape.FlatAppearance.BorderSize = 0;
            this.btnNewShape.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnNewShape.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.40625F);
            this.btnNewShape.ForeColor = System.Drawing.Color.Black;
            this.btnNewShape.Image = null;
            this.btnNewShape.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnNewShape.ImageDisabled = null;
            this.btnNewShape.ImageHover = null;
            this.btnNewShape.ImageNormal = null;
            this.btnNewShape.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnNewShape.ImagePressed = null;
            this.btnNewShape.ImageTextSpacing = 6;
            this.btnNewShape.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnNewShape.ImageTintHover = System.Drawing.Color.Empty;
            this.btnNewShape.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnNewShape.ImageTintOpacity = 0.5F;
            this.btnNewShape.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnNewShape.IsCLick = false;
            this.btnNewShape.IsNotChange = true;
            this.btnNewShape.IsRect = false;
            this.btnNewShape.IsUnGroup = true;
            this.btnNewShape.Location = new System.Drawing.Point(215, 5);
            this.btnNewShape.Margin = new System.Windows.Forms.Padding(0, 0, 3, 0);
            this.btnNewShape.Multiline = false;
            this.btnNewShape.Name = "btnNewShape";
            this.btnNewShape.Size = new System.Drawing.Size(207, 35);
            this.btnNewShape.TabIndex = 3;
            this.btnNewShape.Text = "New Shape";
            this.btnNewShape.TextColor = System.Drawing.Color.Black;
            this.btnNewShape.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnNewShape.UseVisualStyleBackColor = false;
            this.btnNewShape.Click += new System.EventHandler(this.btnNewShape_Click);
            // 
            // tableLayoutPanel5
            // 
            this.tableLayoutPanel5.BackColor = System.Drawing.Color.White;
            this.tableLayoutPanel5.ColumnCount = 6;
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel5.Controls.Add(this.btnPolygon, 4, 0);
            this.tableLayoutPanel5.Controls.Add(this.btnHexagon, 3, 0);
            this.tableLayoutPanel5.Controls.Add(this.btnElip, 2, 0);
            this.tableLayoutPanel5.Controls.Add(this.btnRect, 1, 0);
            this.tableLayoutPanel5.Controls.Add(this.btnNone, 5, 0);
            this.tableLayoutPanel5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel5.Location = new System.Drawing.Point(6, 212);
            this.tableLayoutPanel5.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.tableLayoutPanel5.Name = "tableLayoutPanel5";
            this.tableLayoutPanel5.Padding = new System.Windows.Forms.Padding(3);
            this.tableLayoutPanel5.RowCount = 1;
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel5.Size = new System.Drawing.Size(430, 50);
            this.tableLayoutPanel5.TabIndex = 84;
            // 
            // btnPolygon
            // 
            this.btnPolygon.AutoFont = true;
            this.btnPolygon.AutoFontHeightRatio = 0.75F;
            this.btnPolygon.AutoFontMax = 100F;
            this.btnPolygon.AutoFontMin = 6F;
            this.btnPolygon.AutoFontWidthRatio = 0.92F;
            this.btnPolygon.AutoImage = true;
            this.btnPolygon.AutoImageMaxRatio = 0.75F;
            this.btnPolygon.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnPolygon.AutoImageTint = true;
            this.btnPolygon.BackColor = System.Drawing.Color.White;
            this.btnPolygon.BackgroundColor = System.Drawing.Color.White;
            this.btnPolygon.BorderColor = System.Drawing.Color.White;
            this.btnPolygon.BorderRadius = 10;
            this.btnPolygon.BorderSize = 1;
            this.btnPolygon.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnPolygon.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnPolygon.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnPolygon.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnPolygon.Corner = BeeGlobal.Corner.None;
            this.btnPolygon.DebounceResizeMs = 16;
            this.btnPolygon.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnPolygon.FlatAppearance.BorderSize = 0;
            this.btnPolygon.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnPolygon.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.14063F);
            this.btnPolygon.ForeColor = System.Drawing.Color.Black;
            this.btnPolygon.Image = null;
            this.btnPolygon.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPolygon.ImageDisabled = null;
            this.btnPolygon.ImageHover = null;
            this.btnPolygon.ImageNormal = null;
            this.btnPolygon.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnPolygon.ImagePressed = null;
            this.btnPolygon.ImageTextSpacing = 6;
            this.btnPolygon.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnPolygon.ImageTintHover = System.Drawing.Color.Empty;
            this.btnPolygon.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnPolygon.ImageTintOpacity = 0.5F;
            this.btnPolygon.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnPolygon.IsCLick = false;
            this.btnPolygon.IsNotChange = false;
            this.btnPolygon.IsRect = false;
            this.btnPolygon.IsUnGroup = false;
            this.btnPolygon.Location = new System.Drawing.Point(255, 3);
            this.btnPolygon.Margin = new System.Windows.Forms.Padding(0);
            this.btnPolygon.Multiline = false;
            this.btnPolygon.Name = "btnPolygon";
            this.btnPolygon.Size = new System.Drawing.Size(84, 44);
            this.btnPolygon.TabIndex = 60;
            this.btnPolygon.Text = "Polygon";
            this.btnPolygon.TextColor = System.Drawing.Color.Black;
            this.btnPolygon.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnPolygon.UseVisualStyleBackColor = false;
            this.btnPolygon.Click += new System.EventHandler(this.btnPolygon_Click);
            // 
            // btnHexagon
            // 
            this.btnHexagon.AutoFont = true;
            this.btnHexagon.AutoFontHeightRatio = 0.75F;
            this.btnHexagon.AutoFontMax = 100F;
            this.btnHexagon.AutoFontMin = 6F;
            this.btnHexagon.AutoFontWidthRatio = 0.92F;
            this.btnHexagon.AutoImage = true;
            this.btnHexagon.AutoImageMaxRatio = 0.75F;
            this.btnHexagon.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnHexagon.AutoImageTint = true;
            this.btnHexagon.BackColor = System.Drawing.Color.White;
            this.btnHexagon.BackgroundColor = System.Drawing.Color.White;
            this.btnHexagon.BorderColor = System.Drawing.Color.White;
            this.btnHexagon.BorderRadius = 10;
            this.btnHexagon.BorderSize = 1;
            this.btnHexagon.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnHexagon.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnHexagon.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnHexagon.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnHexagon.Corner = BeeGlobal.Corner.None;
            this.btnHexagon.DebounceResizeMs = 16;
            this.btnHexagon.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnHexagon.FlatAppearance.BorderSize = 0;
            this.btnHexagon.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnHexagon.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.671875F);
            this.btnHexagon.ForeColor = System.Drawing.Color.Black;
            this.btnHexagon.Image = null;
            this.btnHexagon.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHexagon.ImageDisabled = null;
            this.btnHexagon.ImageHover = null;
            this.btnHexagon.ImageNormal = null;
            this.btnHexagon.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnHexagon.ImagePressed = null;
            this.btnHexagon.ImageTextSpacing = 6;
            this.btnHexagon.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnHexagon.ImageTintHover = System.Drawing.Color.Empty;
            this.btnHexagon.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnHexagon.ImageTintOpacity = 0.5F;
            this.btnHexagon.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnHexagon.IsCLick = false;
            this.btnHexagon.IsNotChange = false;
            this.btnHexagon.IsRect = false;
            this.btnHexagon.IsUnGroup = false;
            this.btnHexagon.Location = new System.Drawing.Point(171, 3);
            this.btnHexagon.Margin = new System.Windows.Forms.Padding(0);
            this.btnHexagon.Multiline = false;
            this.btnHexagon.Name = "btnHexagon";
            this.btnHexagon.Size = new System.Drawing.Size(84, 44);
            this.btnHexagon.TabIndex = 59;
            this.btnHexagon.Text = "Hexagon";
            this.btnHexagon.TextColor = System.Drawing.Color.Black;
            this.btnHexagon.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnHexagon.UseVisualStyleBackColor = false;
            this.btnHexagon.Click += new System.EventHandler(this.btnHexagon_Click);
            // 
            // btnElip
            // 
            this.btnElip.AutoFont = true;
            this.btnElip.AutoFontHeightRatio = 0.75F;
            this.btnElip.AutoFontMax = 100F;
            this.btnElip.AutoFontMin = 6F;
            this.btnElip.AutoFontWidthRatio = 0.92F;
            this.btnElip.AutoImage = true;
            this.btnElip.AutoImageMaxRatio = 0.75F;
            this.btnElip.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnElip.AutoImageTint = true;
            this.btnElip.BackColor = System.Drawing.Color.White;
            this.btnElip.BackgroundColor = System.Drawing.Color.White;
            this.btnElip.BorderColor = System.Drawing.Color.White;
            this.btnElip.BorderRadius = 10;
            this.btnElip.BorderSize = 1;
            this.btnElip.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnElip.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnElip.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnElip.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnElip.Corner = BeeGlobal.Corner.None;
            this.btnElip.DebounceResizeMs = 16;
            this.btnElip.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnElip.FlatAppearance.BorderSize = 0;
            this.btnElip.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnElip.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.07813F);
            this.btnElip.ForeColor = System.Drawing.Color.Black;
            this.btnElip.Image = null;
            this.btnElip.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnElip.ImageDisabled = null;
            this.btnElip.ImageHover = null;
            this.btnElip.ImageNormal = null;
            this.btnElip.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnElip.ImagePressed = null;
            this.btnElip.ImageTextSpacing = 6;
            this.btnElip.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnElip.ImageTintHover = System.Drawing.Color.Empty;
            this.btnElip.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnElip.ImageTintOpacity = 0.5F;
            this.btnElip.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnElip.IsCLick = false;
            this.btnElip.IsNotChange = false;
            this.btnElip.IsRect = false;
            this.btnElip.IsUnGroup = false;
            this.btnElip.Location = new System.Drawing.Point(87, 3);
            this.btnElip.Margin = new System.Windows.Forms.Padding(0);
            this.btnElip.Multiline = false;
            this.btnElip.Name = "btnElip";
            this.btnElip.Size = new System.Drawing.Size(84, 44);
            this.btnElip.TabIndex = 3;
            this.btnElip.Text = "Elip";
            this.btnElip.TextColor = System.Drawing.Color.Black;
            this.btnElip.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnElip.UseVisualStyleBackColor = false;
            this.btnElip.Click += new System.EventHandler(this.btnElip_Click);
            // 
            // btnRect
            // 
            this.btnRect.AutoFont = true;
            this.btnRect.AutoFontHeightRatio = 0.75F;
            this.btnRect.AutoFontMax = 100F;
            this.btnRect.AutoFontMin = 6F;
            this.btnRect.AutoFontWidthRatio = 0.92F;
            this.btnRect.AutoImage = true;
            this.btnRect.AutoImageMaxRatio = 0.75F;
            this.btnRect.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnRect.AutoImageTint = true;
            this.btnRect.BackColor = System.Drawing.Color.White;
            this.btnRect.BackgroundColor = System.Drawing.Color.White;
            this.btnRect.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnRect.BorderColor = System.Drawing.Color.White;
            this.btnRect.BorderRadius = 10;
            this.btnRect.BorderSize = 1;
            this.btnRect.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnRect.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnRect.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnRect.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnRect.Corner = BeeGlobal.Corner.Left;
            this.btnRect.DebounceResizeMs = 16;
            this.btnRect.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnRect.FlatAppearance.BorderSize = 0;
            this.btnRect.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnRect.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.203125F);
            this.btnRect.ForeColor = System.Drawing.Color.Black;
            this.btnRect.Image = null;
            this.btnRect.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRect.ImageDisabled = null;
            this.btnRect.ImageHover = null;
            this.btnRect.ImageNormal = null;
            this.btnRect.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnRect.ImagePressed = null;
            this.btnRect.ImageTextSpacing = 6;
            this.btnRect.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnRect.ImageTintHover = System.Drawing.Color.Empty;
            this.btnRect.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnRect.ImageTintOpacity = 0.5F;
            this.btnRect.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnRect.IsCLick = true;
            this.btnRect.IsNotChange = false;
            this.btnRect.IsRect = false;
            this.btnRect.IsUnGroup = false;
            this.btnRect.Location = new System.Drawing.Point(8, 3);
            this.btnRect.Margin = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.btnRect.Multiline = false;
            this.btnRect.Name = "btnRect";
            this.btnRect.Size = new System.Drawing.Size(79, 44);
            this.btnRect.TabIndex = 4;
            this.btnRect.Text = "Rectangle";
            this.btnRect.TextColor = System.Drawing.Color.Black;
            this.btnRect.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnRect.UseVisualStyleBackColor = false;
            this.btnRect.Click += new System.EventHandler(this.btnRect_Click);
            // 
            // btnNone
            // 
            this.btnNone.AutoFont = true;
            this.btnNone.AutoFontHeightRatio = 0.75F;
            this.btnNone.AutoFontMax = 100F;
            this.btnNone.AutoFontMin = 6F;
            this.btnNone.AutoFontWidthRatio = 0.92F;
            this.btnNone.AutoImage = true;
            this.btnNone.AutoImageMaxRatio = 0.75F;
            this.btnNone.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnNone.AutoImageTint = true;
            this.btnNone.BackColor = System.Drawing.Color.White;
            this.btnNone.BackgroundColor = System.Drawing.Color.White;
            this.btnNone.BorderColor = System.Drawing.Color.White;
            this.btnNone.BorderRadius = 10;
            this.btnNone.BorderSize = 1;
            this.btnNone.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnNone.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnNone.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnNone.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnNone.Corner = BeeGlobal.Corner.Right;
            this.btnNone.DebounceResizeMs = 16;
            this.btnNone.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnNone.FlatAppearance.BorderSize = 0;
            this.btnNone.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnNone.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.07813F);
            this.btnNone.ForeColor = System.Drawing.Color.Black;
            this.btnNone.Image = null;
            this.btnNone.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnNone.ImageDisabled = null;
            this.btnNone.ImageHover = null;
            this.btnNone.ImageNormal = null;
            this.btnNone.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnNone.ImagePressed = null;
            this.btnNone.ImageTextSpacing = 6;
            this.btnNone.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnNone.ImageTintHover = System.Drawing.Color.Empty;
            this.btnNone.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnNone.ImageTintOpacity = 0.5F;
            this.btnNone.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnNone.IsCLick = false;
            this.btnNone.IsNotChange = false;
            this.btnNone.IsRect = false;
            this.btnNone.IsUnGroup = false;
            this.btnNone.Location = new System.Drawing.Point(339, 3);
            this.btnNone.Margin = new System.Windows.Forms.Padding(0, 0, 5, 0);
            this.btnNone.Multiline = false;
            this.btnNone.Name = "btnNone";
            this.btnNone.Size = new System.Drawing.Size(83, 44);
            this.btnNone.TabIndex = 5;
            this.btnNone.Text = "None";
            this.btnNone.TextColor = System.Drawing.Color.Black;
            this.btnNone.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnNone.UseVisualStyleBackColor = false;
            this.btnNone.Click += new System.EventHandler(this.btnNone_Click);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.White;
            this.label3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(6, 188);
            this.label3.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(430, 24);
            this.label3.TabIndex = 83;
            this.label3.Text = "Shape";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.BackColor = System.Drawing.Color.White;
            this.tableLayoutPanel3.ColumnCount = 3;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32.35294F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 35.29412F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32.35294F));
            this.tableLayoutPanel3.Controls.Add(this.btnMask, 2, 0);
            this.tableLayoutPanel3.Controls.Add(this.btnCrop, 0, 0);
            this.tableLayoutPanel3.Controls.Add(this.btnArea, 1, 0);
            this.tableLayoutPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel3.Location = new System.Drawing.Point(6, 133);
            this.tableLayoutPanel3.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.Padding = new System.Windows.Forms.Padding(5);
            this.tableLayoutPanel3.RowCount = 1;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(430, 55);
            this.tableLayoutPanel3.TabIndex = 82;
            // 
            // btnMask
            // 
            this.btnMask.AutoFont = true;
            this.btnMask.AutoFontHeightRatio = 0.75F;
            this.btnMask.AutoFontMax = 100F;
            this.btnMask.AutoFontMin = 6F;
            this.btnMask.AutoFontWidthRatio = 0.92F;
            this.btnMask.AutoImage = true;
            this.btnMask.AutoImageMaxRatio = 0.75F;
            this.btnMask.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnMask.AutoImageTint = true;
            this.btnMask.BackColor = System.Drawing.Color.White;
            this.btnMask.BackgroundColor = System.Drawing.Color.White;
            this.btnMask.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnMask.BackgroundImage")));
            this.btnMask.BorderColor = System.Drawing.Color.White;
            this.btnMask.BorderRadius = 10;
            this.btnMask.BorderSize = 1;
            this.btnMask.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnMask.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnMask.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnMask.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnMask.Corner = BeeGlobal.Corner.Right;
            this.btnMask.DebounceResizeMs = 16;
            this.btnMask.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnMask.FlatAppearance.BorderSize = 0;
            this.btnMask.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnMask.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.07813F);
            this.btnMask.ForeColor = System.Drawing.Color.Black;
            this.btnMask.Image = null;
            this.btnMask.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMask.ImageDisabled = null;
            this.btnMask.ImageHover = null;
            this.btnMask.ImageNormal = null;
            this.btnMask.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnMask.ImagePressed = null;
            this.btnMask.ImageTextSpacing = 6;
            this.btnMask.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnMask.ImageTintHover = System.Drawing.Color.Empty;
            this.btnMask.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnMask.ImageTintOpacity = 0.5F;
            this.btnMask.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnMask.IsCLick = false;
            this.btnMask.IsNotChange = false;
            this.btnMask.IsRect = false;
            this.btnMask.IsUnGroup = false;
            this.btnMask.Location = new System.Drawing.Point(288, 5);
            this.btnMask.Margin = new System.Windows.Forms.Padding(0);
            this.btnMask.Multiline = false;
            this.btnMask.Name = "btnMask";
            this.btnMask.Size = new System.Drawing.Size(137, 45);
            this.btnMask.TabIndex = 4;
            this.btnMask.Text = "Area Mask";
            this.btnMask.TextColor = System.Drawing.Color.Black;
            this.btnMask.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnMask.UseVisualStyleBackColor = false;
            this.btnMask.Click += new System.EventHandler(this.btnClear_Click);
            // 
            // btnCrop
            // 
            this.btnCrop.AutoFont = true;
            this.btnCrop.AutoFontHeightRatio = 0.75F;
            this.btnCrop.AutoFontMax = 100F;
            this.btnCrop.AutoFontMin = 6F;
            this.btnCrop.AutoFontWidthRatio = 0.92F;
            this.btnCrop.AutoImage = true;
            this.btnCrop.AutoImageMaxRatio = 0.75F;
            this.btnCrop.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnCrop.AutoImageTint = true;
            this.btnCrop.BackColor = System.Drawing.Color.White;
            this.btnCrop.BackgroundColor = System.Drawing.Color.White;
            this.btnCrop.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCrop.BackgroundImage")));
            this.btnCrop.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnCrop.BorderColor = System.Drawing.Color.White;
            this.btnCrop.BorderRadius = 10;
            this.btnCrop.BorderSize = 1;
            this.btnCrop.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnCrop.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnCrop.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnCrop.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnCrop.Corner = BeeGlobal.Corner.Left;
            this.btnCrop.DebounceResizeMs = 16;
            this.btnCrop.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnCrop.FlatAppearance.BorderSize = 0;
            this.btnCrop.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCrop.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.07813F);
            this.btnCrop.ForeColor = System.Drawing.Color.Black;
            this.btnCrop.Image = null;
            this.btnCrop.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCrop.ImageDisabled = null;
            this.btnCrop.ImageHover = null;
            this.btnCrop.ImageNormal = null;
            this.btnCrop.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnCrop.ImagePressed = null;
            this.btnCrop.ImageTextSpacing = 6;
            this.btnCrop.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnCrop.ImageTintHover = System.Drawing.Color.Empty;
            this.btnCrop.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnCrop.ImageTintOpacity = 0.5F;
            this.btnCrop.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnCrop.IsCLick = false;
            this.btnCrop.IsNotChange = false;
            this.btnCrop.IsRect = false;
            this.btnCrop.IsUnGroup = false;
            this.btnCrop.Location = new System.Drawing.Point(5, 5);
            this.btnCrop.Margin = new System.Windows.Forms.Padding(0);
            this.btnCrop.Multiline = false;
            this.btnCrop.Name = "btnCrop";
            this.btnCrop.Size = new System.Drawing.Size(135, 45);
            this.btnCrop.TabIndex = 2;
            this.btnCrop.Text = "Scan";
            this.btnCrop.TextColor = System.Drawing.Color.Black;
            this.btnCrop.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnCrop.UseVisualStyleBackColor = false;
            this.btnCrop.Click += new System.EventHandler(this.btnCropRect_Click);
            // 
            // btnArea
            // 
            this.btnArea.AutoFont = true;
            this.btnArea.AutoFontHeightRatio = 0.75F;
            this.btnArea.AutoFontMax = 100F;
            this.btnArea.AutoFontMin = 6F;
            this.btnArea.AutoFontWidthRatio = 0.92F;
            this.btnArea.AutoImage = true;
            this.btnArea.AutoImageMaxRatio = 0.75F;
            this.btnArea.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnArea.AutoImageTint = true;
            this.btnArea.BackColor = System.Drawing.Color.White;
            this.btnArea.BackgroundColor = System.Drawing.Color.White;
            this.btnArea.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnArea.BackgroundImage")));
            this.btnArea.BorderColor = System.Drawing.Color.White;
            this.btnArea.BorderRadius = 5;
            this.btnArea.BorderSize = 1;
            this.btnArea.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnArea.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnArea.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnArea.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnArea.Corner = BeeGlobal.Corner.None;
            this.btnArea.DebounceResizeMs = 16;
            this.btnArea.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnArea.FlatAppearance.BorderSize = 0;
            this.btnArea.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnArea.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.07813F);
            this.btnArea.ForeColor = System.Drawing.Color.Black;
            this.btnArea.Image = null;
            this.btnArea.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnArea.ImageDisabled = null;
            this.btnArea.ImageHover = null;
            this.btnArea.ImageNormal = null;
            this.btnArea.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnArea.ImagePressed = null;
            this.btnArea.ImageTextSpacing = 6;
            this.btnArea.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnArea.ImageTintHover = System.Drawing.Color.Empty;
            this.btnArea.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnArea.ImageTintOpacity = 0.5F;
            this.btnArea.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnArea.IsCLick = true;
            this.btnArea.IsNotChange = false;
            this.btnArea.IsRect = false;
            this.btnArea.IsUnGroup = false;
            this.btnArea.Location = new System.Drawing.Point(140, 5);
            this.btnArea.Margin = new System.Windows.Forms.Padding(0);
            this.btnArea.Multiline = false;
            this.btnArea.Name = "btnArea";
            this.btnArea.Size = new System.Drawing.Size(148, 45);
            this.btnArea.TabIndex = 3;
            this.btnArea.Text = "Area Check";
            this.btnArea.TextColor = System.Drawing.Color.Black;
            this.btnArea.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnArea.UseVisualStyleBackColor = false;
            this.btnArea.Click += new System.EventHandler(this.btnCropArea_Click);
            // 
            // label1
            // 
            this.label1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            this.label1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.Transparent;
            this.label1.Location = new System.Drawing.Point(6, 101);
            this.label1.Margin = new System.Windows.Forms.Padding(5, 10, 5, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(430, 32);
            this.label1.TabIndex = 81;
            this.label1.Text = "Choose Area";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // trackScore
            // 
            this.trackScore.AutoRepeatAccelDeltaMs = -5;
            this.trackScore.AutoRepeatAccelerate = true;
            this.trackScore.AutoRepeatEnabled = true;
            this.trackScore.AutoRepeatInitialDelay = 400;
            this.trackScore.AutoRepeatInterval = 60;
            this.trackScore.AutoRepeatMinInterval = 20;
            this.trackScore.AutoShowTextbox = true;
            this.trackScore.AutoSizeTextbox = true;
            this.trackScore.BackColor = System.Drawing.Color.White;
            this.trackScore.BarLeftGap = 20;
            this.trackScore.BarRightGap = 6;
            this.trackScore.ChromeGap = 1;
            this.trackScore.ChromeWidthRatio = 0.14F;
            this.trackScore.ColorBorder = System.Drawing.Color.LightGray;
            this.trackScore.ColorFill = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(213)))), ((int)(((byte)(143)))));
            this.trackScore.ColorScale = System.Drawing.Color.LightGray;
            this.trackScore.ColorThumb = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.trackScore.ColorThumbBorder = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(201)))), ((int)(((byte)(110)))));
            this.trackScore.ColorTrack = System.Drawing.Color.LightGray;
            this.trackScore.Decimals = 0;
            this.trackScore.DisabledDesaturateMix = 0.3F;
            this.trackScore.DisabledDimFactor = 0.9F;
            this.trackScore.Dock = System.Windows.Forms.DockStyle.Fill;
            this.trackScore.EdgePadding = 2;
            this.trackScore.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.trackScore.InnerPadding = new System.Windows.Forms.Padding(10, 6, 10, 6);
            this.trackScore.KeyboardStep = 1F;
            this.trackScore.Location = new System.Drawing.Point(6, 772);
            this.trackScore.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.trackScore.MatchTextboxFontToThumb = true;
            this.trackScore.Max = 100F;
            this.trackScore.MaxTextboxWidth = 0;
            this.trackScore.MaxThumb = 1000;
            this.trackScore.MaxTrackHeight = 1000;
            this.trackScore.Min = 0F;
            this.trackScore.MinChromeWidth = 64;
            this.trackScore.MinimumSize = new System.Drawing.Size(140, 36);
            this.trackScore.MinTextboxWidth = 32;
            this.trackScore.MinThumb = 30;
            this.trackScore.MinTrackHeight = 8;
            this.trackScore.Name = "trackScore";
            this.trackScore.Radius = 8;
            this.trackScore.ShowValueOnThumb = true;
            this.trackScore.Size = new System.Drawing.Size(430, 53);
            this.trackScore.SnapToStep = true;
            this.trackScore.StartWithTextboxHidden = true;
            this.trackScore.Step = 1F;
            this.trackScore.TabIndex = 80;
            this.trackScore.TextboxFontSize = 22F;
            this.trackScore.TextboxSidePadding = 10;
            this.trackScore.TextboxWidth = 600;
            this.trackScore.ThumbDiameterRatio = 2F;
            this.trackScore.ThumbValueBold = true;
            this.trackScore.ThumbValueFontScale = 1.5F;
            this.trackScore.ThumbValuePadding = 0;
            this.trackScore.TightEdges = true;
            this.trackScore.TrackHeightRatio = 0.45F;
            this.trackScore.TrackWidthRatio = 1F;
            this.trackScore.UnitText = "";
            this.trackScore.Value = 0F;
            this.trackScore.WheelStep = 1F;
            this.trackScore.ValueChanged += new System.Action<float>(this.trackScore_ValueChanged);
            // 
            // label8
            // 
            this.label8.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            this.label8.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label8.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.Color.Transparent;
            this.label8.Location = new System.Drawing.Point(6, 740);
            this.label8.Margin = new System.Windows.Forms.Padding(5, 10, 5, 0);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(430, 32);
            this.label8.TabIndex = 77;
            this.label8.Text = "Tolerance";
            this.label8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label7
            // 
            this.label7.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            this.label7.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.Transparent;
            this.label7.Location = new System.Drawing.Point(6, 5);
            this.label7.Margin = new System.Windows.Forms.Padding(5, 5, 5, 0);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(430, 32);
            this.label7.TabIndex = 71;
            this.label7.Text = "Search Range";
            this.label7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.BackColor = System.Drawing.Color.White;
            this.tableLayoutPanel2.ColumnCount = 2;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.Controls.Add(this.btnCropFull, 1, 0);
            this.tableLayoutPanel2.Controls.Add(this.btnCropHalt, 0, 0);
            this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel2.Location = new System.Drawing.Point(6, 37);
            this.tableLayoutPanel2.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.Padding = new System.Windows.Forms.Padding(5);
            this.tableLayoutPanel2.RowCount = 1;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 44F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(430, 54);
            this.tableLayoutPanel2.TabIndex = 39;
            // 
            // btnCropFull
            // 
            this.btnCropFull.AutoFont = true;
            this.btnCropFull.AutoFontHeightRatio = 0.75F;
            this.btnCropFull.AutoFontMax = 100F;
            this.btnCropFull.AutoFontMin = 6F;
            this.btnCropFull.AutoFontWidthRatio = 0.92F;
            this.btnCropFull.AutoImage = true;
            this.btnCropFull.AutoImageMaxRatio = 0.75F;
            this.btnCropFull.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnCropFull.AutoImageTint = true;
            this.btnCropFull.BackColor = System.Drawing.Color.White;
            this.btnCropFull.BackgroundColor = System.Drawing.Color.White;
            this.btnCropFull.BorderColor = System.Drawing.Color.White;
            this.btnCropFull.BorderRadius = 10;
            this.btnCropFull.BorderSize = 1;
            this.btnCropFull.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnCropFull.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnCropFull.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnCropFull.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnCropFull.Corner = BeeGlobal.Corner.Right;
            this.btnCropFull.DebounceResizeMs = 16;
            this.btnCropFull.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnCropFull.FlatAppearance.BorderSize = 0;
            this.btnCropFull.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCropFull.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.07813F);
            this.btnCropFull.ForeColor = System.Drawing.Color.Black;
            this.btnCropFull.Image = null;
            this.btnCropFull.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCropFull.ImageDisabled = null;
            this.btnCropFull.ImageHover = null;
            this.btnCropFull.ImageNormal = null;
            this.btnCropFull.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnCropFull.ImagePressed = null;
            this.btnCropFull.ImageTextSpacing = 6;
            this.btnCropFull.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnCropFull.ImageTintHover = System.Drawing.Color.Empty;
            this.btnCropFull.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnCropFull.ImageTintOpacity = 0.5F;
            this.btnCropFull.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnCropFull.IsCLick = false;
            this.btnCropFull.IsNotChange = false;
            this.btnCropFull.IsRect = false;
            this.btnCropFull.IsUnGroup = false;
            this.btnCropFull.Location = new System.Drawing.Point(215, 5);
            this.btnCropFull.Margin = new System.Windows.Forms.Padding(0, 0, 3, 0);
            this.btnCropFull.Multiline = false;
            this.btnCropFull.Name = "btnCropFull";
            this.btnCropFull.Size = new System.Drawing.Size(207, 44);
            this.btnCropFull.TabIndex = 3;
            this.btnCropFull.Text = "Partial";
            this.btnCropFull.TextColor = System.Drawing.Color.Black;
            this.btnCropFull.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnCropFull.UseVisualStyleBackColor = false;
            this.btnCropFull.Click += new System.EventHandler(this.btnCropFull_Click);
            // 
            // btnCropHalt
            // 
            this.btnCropHalt.AutoFont = true;
            this.btnCropHalt.AutoFontHeightRatio = 0.75F;
            this.btnCropHalt.AutoFontMax = 100F;
            this.btnCropHalt.AutoFontMin = 6F;
            this.btnCropHalt.AutoFontWidthRatio = 0.92F;
            this.btnCropHalt.AutoImage = true;
            this.btnCropHalt.AutoImageMaxRatio = 0.75F;
            this.btnCropHalt.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnCropHalt.AutoImageTint = true;
            this.btnCropHalt.BackColor = System.Drawing.Color.White;
            this.btnCropHalt.BackgroundColor = System.Drawing.Color.White;
            this.btnCropHalt.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnCropHalt.BorderColor = System.Drawing.Color.White;
            this.btnCropHalt.BorderRadius = 10;
            this.btnCropHalt.BorderSize = 1;
            this.btnCropHalt.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnCropHalt.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnCropHalt.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnCropHalt.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnCropHalt.Corner = BeeGlobal.Corner.Left;
            this.btnCropHalt.DebounceResizeMs = 16;
            this.btnCropHalt.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnCropHalt.FlatAppearance.BorderSize = 0;
            this.btnCropHalt.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCropHalt.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.07813F);
            this.btnCropHalt.ForeColor = System.Drawing.Color.Black;
            this.btnCropHalt.Image = null;
            this.btnCropHalt.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCropHalt.ImageDisabled = null;
            this.btnCropHalt.ImageHover = null;
            this.btnCropHalt.ImageNormal = null;
            this.btnCropHalt.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnCropHalt.ImagePressed = null;
            this.btnCropHalt.ImageTextSpacing = 6;
            this.btnCropHalt.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnCropHalt.ImageTintHover = System.Drawing.Color.Empty;
            this.btnCropHalt.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnCropHalt.ImageTintOpacity = 0.5F;
            this.btnCropHalt.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnCropHalt.IsCLick = true;
            this.btnCropHalt.IsNotChange = false;
            this.btnCropHalt.IsRect = false;
            this.btnCropHalt.IsUnGroup = false;
            this.btnCropHalt.Location = new System.Drawing.Point(8, 5);
            this.btnCropHalt.Margin = new System.Windows.Forms.Padding(3, 0, 0, 0);
            this.btnCropHalt.Multiline = false;
            this.btnCropHalt.Name = "btnCropHalt";
            this.btnCropHalt.Size = new System.Drawing.Size(207, 44);
            this.btnCropHalt.TabIndex = 2;
            this.btnCropHalt.Text = "Entire";
            this.btnCropHalt.TextColor = System.Drawing.Color.Black;
            this.btnCropHalt.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnCropHalt.UseVisualStyleBackColor = false;
            this.btnCropHalt.Click += new System.EventHandler(this.btnCropHalt_Click);
            // 
            // pInspect
            // 
            this.pInspect.Controls.Add(this.btnTest);
            this.pInspect.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.pInspect.Location = new System.Drawing.Point(0, 777);
            this.pInspect.Name = "pInspect";
            this.pInspect.Padding = new System.Windows.Forms.Padding(10);
            this.pInspect.Size = new System.Drawing.Size(468, 100);
            this.pInspect.TabIndex = 82;
            // 
            // btnTest
            // 
            this.btnTest.AutoFont = false;
            this.btnTest.AutoFontHeightRatio = 0.75F;
            this.btnTest.AutoFontMax = 100F;
            this.btnTest.AutoFontMin = 6F;
            this.btnTest.AutoFontWidthRatio = 0.92F;
            this.btnTest.AutoImage = true;
            this.btnTest.AutoImageMaxRatio = 0.75F;
            this.btnTest.AutoImageMode = BeeInterface.RJButton.ImageFitMode.Contain;
            this.btnTest.AutoImageTint = true;
            this.btnTest.BackColor = System.Drawing.SystemColors.Control;
            this.btnTest.BackgroundColor = System.Drawing.SystemColors.Control;
            this.btnTest.BorderColor = System.Drawing.SystemColors.Control;
            this.btnTest.BorderRadius = 10;
            this.btnTest.BorderSize = 1;
            this.btnTest.ClickBotColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(211)))), ((int)(((byte)(139)))));
            this.btnTest.ClickMidColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(204)))), ((int)(((byte)(120)))));
            this.btnTest.ClickTopColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(192)))), ((int)(((byte)(89)))));
            this.btnTest.ContentPadding = new System.Windows.Forms.Padding(8, 6, 8, 6);
            this.btnTest.Corner = BeeGlobal.Corner.Both;
            this.btnTest.DebounceResizeMs = 16;
            this.btnTest.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnTest.FlatAppearance.BorderSize = 0;
            this.btnTest.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnTest.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnTest.ForeColor = System.Drawing.Color.Black;
            this.btnTest.Image = null;
            this.btnTest.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTest.ImageDisabled = null;
            this.btnTest.ImageHover = null;
            this.btnTest.ImageNormal = null;
            this.btnTest.ImagePadding = new System.Windows.Forms.Padding(1);
            this.btnTest.ImagePressed = null;
            this.btnTest.ImageTextSpacing = 6;
            this.btnTest.ImageTintDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnTest.ImageTintHover = System.Drawing.Color.Empty;
            this.btnTest.ImageTintNormal = System.Drawing.Color.Empty;
            this.btnTest.ImageTintOpacity = 0.5F;
            this.btnTest.ImageTintPressed = System.Drawing.Color.Empty;
            this.btnTest.IsCLick = false;
            this.btnTest.IsNotChange = true;
            this.btnTest.IsRect = false;
            this.btnTest.IsUnGroup = true;
            this.btnTest.Location = new System.Drawing.Point(10, 10);
            this.btnTest.Margin = new System.Windows.Forms.Padding(10);
            this.btnTest.Multiline = false;
            this.btnTest.Name = "btnTest";
            this.btnTest.Size = new System.Drawing.Size(448, 80);
            this.btnTest.TabIndex = 81;
            this.btnTest.Text = "Inspect";
            this.btnTest.TextColor = System.Drawing.Color.Black;
            this.btnTest.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnTest.UseVisualStyleBackColor = false;
            this.btnTest.Click += new System.EventHandler(this.btnTest_Click);
            // 
            // oK_Cancel1
            // 
            this.oK_Cancel1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.oK_Cancel1.Location = new System.Drawing.Point(0, 877);
            this.oK_Cancel1.Name = "oK_Cancel1";
            this.oK_Cancel1.Size = new System.Drawing.Size(468, 62);
            this.oK_Cancel1.TabIndex = 18;
            // 
            // ToolBarcode
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ButtonHighlight;
            this.Controls.Add(this.tabControl2);
            this.Controls.Add(this.pInspect);
            this.Controls.Add(this.oK_Cancel1);
            this.DoubleBuffered = true;
            this.Name = "ToolBarcode";
            this.Size = new System.Drawing.Size(468, 939);
            this.tabControl2.ResumeLayout(false);
            this.tabP1.ResumeLayout(false);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel1.PerformLayout();
            this.tableLayoutPanel7.ResumeLayout(false);
            this.lay3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.imgTemp)).EndInit();
            this.tableLayoutPanel4.ResumeLayout(false);
            this.tableLayoutPanel4.PerformLayout();
            this.tableLayoutPanel6.ResumeLayout(false);
            this.tableLayoutPanel5.ResumeLayout(false);
            this.tableLayoutPanel3.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            this.pInspect.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.TabControl tabControl2;
        private System.Windows.Forms.TabPage tabP1;
        private GroupControl.OK_Cancel oK_Cancel1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private RJButton btnCropFull;
        private RJButton btnCropHalt;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private AdjustBarEx trackScore;
        private System.Windows.Forms.Panel pInspect;
        private RJButton btnTest;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private RJButton btnMask;
        private RJButton btnCrop;
        private RJButton btnArea;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel5;
        private RJButton btnPolygon;
        private RJButton btnHexagon;
        private RJButton btnElip;
        private RJButton btnRect;
        private RJButton btnNone;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel6;
        private RJButton btnNewShape;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel4;
        private System.Windows.Forms.Label label4;
        private RJButton btnBlack;
        private RJButton btnWhite;
        private RJButton btnChooseOCR;
        private RJButton btnScanOCR;
        private System.Windows.Forms.TableLayoutPanel lay3;
        private System.Windows.Forms.PictureBox imgTemp;
        private AdjustBarEx AdjOffSetArea;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel7;
    }
}
