#define VER_MAJOR 1
#define VER_MINOR 0
#define VER_BUILD 0
#define VER_REV 1
#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)
#define FILEVER_STR STR(VER_MAJOR) "." STR(VER_MINOR) "." STR(VER_BUILD) "." STR(VER_REV)
#define VER_FILE_VERSION VER_MAJOR, VER_MINOR, VER_BUILD, VER_REV
#define VER_FILE_VERSION_STR FILEVER_STR
